{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/showGDPRConsentUI()","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"showGDPRConsentUI","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showGDPRConsentUI","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","externalID":"c:objc(cs)PWGDPRManager(im)showGDPRConsentUI","symbolKind":"method","roleHeading":"Instance Method","title":"showGDPRConsentUI()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showGDPRConsentUI"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprconsentui()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprconsentui()"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager","title":"PWGDPRManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWGDPRManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWGDPRManager"}],"url":"\/documentation\/pushwooshframework\/pwgdprmanager","abstract":[],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager/showGDPRConsentUI()":{"role":"symbol","title":"showGDPRConsentUI()","type":"topic","url":"\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprconsentui()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showGDPRConsentUI","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/showGDPRConsentUI()","abstract":[],"navigatorTitle":[{"text":"showGDPRConsentUI","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"showGDPRConsentUI","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showGDPRConsentUI"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"showGDPRConsentUI","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"PWGDPRManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/fragments","value":[{"kind":"identifier","text":"PWGDPRManager"}],"op":"replace"},{"op":"replace","value":"showGDPRConsentUI","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1showGDPRConsentUI()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1showGDPRConsentUI()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showGDPRConsentUI"}]}]}]}