{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmedia\/source"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmedia\/source"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PWRichMediaSource","kind":"typeIdentifier","text":"PWRichMediaSource"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)PWRichMedia(py)source","role":"symbol","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"source","kind":"identifier"}],"symbolKind":"property","title":"source"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","text":"PWRichMediaSource","kind":"typeIdentifier","preciseIdentifier":"c:@E@PWRichMediaSource"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Rich Media presenter type.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia\/source"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia/source":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@PWRichMediaSource","text":"PWRichMediaSource"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Rich Media presenter type."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia\/source","navigatorTitle":[{"text":"source","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmedia\/source","title":"source"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSource"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource","title":"PWRichMediaSource","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"source","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"source"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","text":"PWRichMediaSource","preciseIdentifier":"c:@E@PWRichMediaSource","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title","op":"replace","value":"PWRichMedia"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments","value":[{"kind":"identifier","text":"PWRichMedia"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia~1source\/title","value":"source"},{"value":[{"kind":"identifier","text":"source"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia~1source\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/title","value":"PWRichMediaSource","op":"replace"},{"op":"replace","value":[{"text":"PWRichMediaSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}