{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation"]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"DismissModalWindowAnimation","symbolKind":"enum","role":"symbol","externalID":"c:@E@DismissModalWindowAnimation","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DismissModalWindowAnimation"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissModalWindowAnimation"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"PWAnimationDismissDown","type":"codeVoice"},{"text":": The modal window slides down when dismissed.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWAnimationDismissUp"},{"text":": The modal window slides up when dismissed.","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"PWAnimationDismissLeft","type":"codeVoice"},{"text":": The modal window slides to the left when dismissed.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWAnimationDismissRight"},{"type":"text","text":": The modal window slides to the right when dismissed."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWAnimationCurveEaseInOut"},{"type":"text","text":": The modal window uses an ease-in-out curve animation when dismissed."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWAnimationDismissNone"},{"type":"text","text":": No animation is applied when dismissing the modal window."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWAnimationDismissDefault"},{"text":": The default dismiss animation is ","type":"text"},{"type":"codeVoice","code":"PWAnimationCurveEaseInOut"},{"type":"text","text":"."}]}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"},"abstract":[{"type":"text","text":"Enum defining the animation styles for dismissing the modal window."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationCurveEaseInOut","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDefault","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDown","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissNone","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissUp"]},{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissDown":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissDown","kind":"identifier"}],"navigatorTitle":[{"text":"PWAnimationDismissDown","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdown","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDown","title":"DismissModalWindowAnimation.PWAnimationDismissDown"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissRight":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissRight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissRight"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissright","role":"symbol","kind":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissRight","type":"topic","navigatorTitle":[{"text":"PWAnimationDismissRight","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/RawRepresentable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/RawRepresentable-Implementations","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/SY":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissNone":{"navigatorTitle":[{"text":"PWAnimationDismissNone","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissnone","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissNone","kind":"identifier"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissNone","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissNone","abstract":[],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissUp":{"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissup","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationDismissUp"}],"navigatorTitle":[{"text":"PWAnimationDismissUp","kind":"identifier"}],"kind":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissUp","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissUp","abstract":[],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/Equatable-Implementations":{"abstract":[],"kind":"article","type":"topic","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationCurveEaseInOut":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationCurveEaseInOut","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationcurveeaseinout","navigatorTitle":[{"text":"PWAnimationCurveEaseInOut","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationCurveEaseInOut"}],"kind":"symbol","role":"symbol","type":"topic","title":"DismissModalWindowAnimation.PWAnimationCurveEaseInOut"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissLeft":{"navigatorTitle":[{"text":"PWAnimationDismissLeft","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissLeft"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissLeft","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissLeft","abstract":[],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/init(rawValue:)":{"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/init(rawValue:)","abstract":[],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissDefault":{"navigatorTitle":[{"kind":"identifier","text":"PWAnimationDismissDefault"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdefault","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissDefault","kind":"identifier"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissDefault","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDefault","abstract":[{"type":"text","text":"Default dismiss animation is "},{"type":"codeVoice","code":"PWAnimationCurveEaseInOut"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"DismissModalWindowAnimation","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}]},{"value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationCurveEaseInOut","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDefault","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDown","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissNone","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissUp"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"PWAnimationDismissDown","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDown\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDown\/fragments","value":[{"text":"PWAnimationDismissDown","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PWAnimationDismissRight","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissRight\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissRight\/fragments","value":[{"text":"PWAnimationDismissRight","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissNone\/title","value":"PWAnimationDismissNone"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissNone\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWAnimationDismissNone"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissUp\/title","value":"PWAnimationDismissUp","op":"replace"},{"value":[{"text":"PWAnimationDismissUp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissUp\/fragments","op":"replace"},{"value":"PWAnimationCurveEaseInOut","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationCurveEaseInOut\/title"},{"value":[{"kind":"identifier","text":"PWAnimationCurveEaseInOut"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationCurveEaseInOut\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title","value":"DismissModalWindowAnimation"},{"value":[{"kind":"identifier","text":"DismissModalWindowAnimation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments"},{"op":"replace","value":"PWAnimationDismissLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissLeft\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissLeft\/fragments","value":[{"kind":"identifier","text":"PWAnimationDismissLeft"}]},{"op":"replace","value":"PWAnimationDismissDefault","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDefault\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDefault\/fragments","value":[{"text":"PWAnimationDismissDefault","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}