{"variants":[{"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"],"kind":"relationships"}],"metadata":{"roleHeading":"Enumeration","title":"HapticFeedbackType","role":"symbol","externalID":"c:@E@HapticFeedbackType","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HapticFeedbackType","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"HapticFeedbackType","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackHard","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackLight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackMedium","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackNone"]},{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HapticFeedbackType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"PWHapticFeedbackLight","type":"codeVoice"},{"text":": Provides a light vibration feedback.","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"PWHapticFeedbackMedium","type":"codeVoice"},{"text":": Provides a medium-intensity vibration feedback.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWHapticFeedbackHard"},{"text":": Provides a strong vibration feedback.","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"PWHapticFeedbackNone","type":"codeVoice"},{"type":"text","text":": Vibration feedback is turned off by default."}],"type":"paragraph"}]}]}],"kind":"content"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/Equatable-Implementations":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/equatable-implementations","abstract":[],"kind":"article"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackMedium":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackMedium","title":"HapticFeedbackType.PWHapticFeedbackMedium","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackmedium","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackMedium"}],"navigatorTitle":[{"text":"PWHapticFeedbackMedium","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/init(rawValue:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/init(rawvalue:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackLight":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackLight","title":"HapticFeedbackType.PWHapticFeedbackLight","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbacklight","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackLight"}],"navigatorTitle":[{"kind":"identifier","text":"PWHapticFeedbackLight"}]},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackHard":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackHard","title":"HapticFeedbackType.PWHapticFeedbackHard","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackhard","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackHard"}],"navigatorTitle":[{"kind":"identifier","text":"PWHapticFeedbackHard"}]},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype","abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"kind":"symbol","title":"HapticFeedbackType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticFeedbackType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HapticFeedbackType"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackNone":{"kind":"symbol","abstract":[{"type":"text","text":"Vibration is off by default."}],"navigatorTitle":[{"kind":"identifier","text":"PWHapticFeedbackNone"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackNone","type":"topic","role":"symbol","title":"HapticFeedbackType.PWHapticFeedbackNone","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbacknone","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWHapticFeedbackNone","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/RawRepresentable-Implementations":{"url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"HapticFeedbackType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"HapticFeedbackType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"HapticFeedbackType","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackHard","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackLight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackMedium","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackNone"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HapticFeedbackType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackMedium\/title","op":"replace","value":"PWHapticFeedbackMedium"},{"op":"replace","value":[{"kind":"identifier","text":"PWHapticFeedbackMedium"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackMedium\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackLight\/title","op":"replace","value":"PWHapticFeedbackLight"},{"op":"replace","value":[{"kind":"identifier","text":"PWHapticFeedbackLight"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackLight\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackHard\/title","op":"replace","value":"PWHapticFeedbackHard"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackHard\/fragments","value":[{"kind":"identifier","text":"PWHapticFeedbackHard"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/title","value":"HapticFeedbackType","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/fragments","value":[{"kind":"identifier","text":"HapticFeedbackType"}],"op":"replace"},{"op":"replace","value":"PWHapticFeedbackNone","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackNone\/title"},{"value":[{"text":"PWHapticFeedbackNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackNone\/fragments"}]}]}