{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Enum defining the possible positions for displaying a modal window.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModalWindowPosition"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"items":[{"content":[{"inlineContent":[{"code":"PWModalWindowPositionTop","type":"codeVoice"},{"type":"text","text":": The modal window appears at the top of the screen, within the safe area."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"PWModalWindowPositionCenter","type":"codeVoice"},{"type":"text","text":": The modal window appears at the center of the screen, within the safe area."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWModalWindowPositionBottom"},{"type":"text","text":": The modal window appears at the bottom of the screen, within the safe area."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"PWModalWindowPositionBottomSheet","type":"codeVoice"},{"type":"text","text":": The modal window appears at the very bottom of the screen, ignoring the safe area."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWModalWindowPositionDefault"},{"text":": The default position is the center of the screen, within the safe area.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"},"variants":[{"paths":["\/documentation\/pushwooshframework\/modalwindowposition"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottom","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottomSheet","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionCenter","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionDefault","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionFullScreen","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionTop"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModalWindowPosition"}],"externalID":"c:@E@ModalWindowPosition","navigatorTitle":[{"text":"ModalWindowPosition","kind":"identifier"}],"role":"symbol","symbolKind":"enum","title":"ModalWindowPosition"},"sections":[],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/Equatable-Implementations":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/pushwooshframework\/modalwindowposition\/equatable-implementations","abstract":[],"kind":"article","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","title":"Swift.Sendable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionCenter":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionCenter","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositioncenter","role":"symbol","title":"ModalWindowPosition.PWModalWindowPositionCenter"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionBottom":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottom","title":"ModalWindowPosition.PWModalWindowPositionBottom","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionbottom","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionBottom"}],"navigatorTitle":[{"text":"PWModalWindowPositionBottom","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionTop":{"title":"ModalWindowPosition.PWModalWindowPositionTop","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionTop","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionTop","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiontop","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PWModalWindowPositionTop","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionBottomSheet":{"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionbottomsheet","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottomSheet","role":"symbol","abstract":[],"type":"topic","title":"ModalWindowPosition.PWModalWindowPositionBottomSheet","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionBottomSheet"}]},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionFullScreen":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"title":"ModalWindowPosition.PWModalWindowPositionFullScreen","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionFullScreen","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionfullscreen"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/pushwooshframework\/modalwindowposition\/rawrepresentable-implementations","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/RawRepresentable-Implementations"},"doc://com.pushwoosh.PushwooshiOS/SY":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionDefault":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionDefault","title":"ModalWindowPosition.PWModalWindowPositionDefault","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiondefault","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionDefault","kind":"identifier"}],"navigatorTitle":[{"text":"PWModalWindowPositionDefault","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/init(rawValue:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/init(rawValue:)","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ModalWindowPosition"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"ModalWindowPosition","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ModalWindowPosition"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottom","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottomSheet","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionCenter","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionDefault","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionFullScreen","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionTop"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModalWindowPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ModalWindowPosition","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title","op":"replace"},{"value":[{"text":"ModalWindowPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionCenter\/title","op":"replace","value":"PWModalWindowPositionCenter"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionCenter\/fragments","op":"replace","value":[{"text":"PWModalWindowPositionCenter","kind":"identifier"}]},{"value":"PWModalWindowPositionBottom","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottom\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottom\/fragments","op":"replace","value":[{"text":"PWModalWindowPositionBottom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionTop\/title","value":"PWModalWindowPositionTop","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionTop\/fragments","value":[{"text":"PWModalWindowPositionTop","kind":"identifier"}]},{"op":"replace","value":"PWModalWindowPositionBottomSheet","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottomSheet\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottomSheet\/fragments","value":[{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionFullScreen\/title","value":"PWModalWindowPositionFullScreen","op":"replace"},{"value":[{"kind":"identifier","text":"PWModalWindowPositionFullScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionFullScreen\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionDefault\/title","value":"PWModalWindowPositionDefault"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionDefault\/fragments","value":[{"text":"PWModalWindowPositionDefault","kind":"identifier"}],"op":"replace"}]}]}