{"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"text":"PresentModalWindowAnimation","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@E@PresentModalWindowAnimation","title":"PresentModalWindowAnimation","roleHeading":"Enumeration"},"variants":[{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"PWAnimationPresentFromBottom","type":"codeVoice"},{"text":": The modal window slides in from the bottom of the screen.","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"PWAnimationPresentFromTop","type":"codeVoice"},{"type":"text","text":": The modal window slides in from the top of the screen."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWAnimationPresentFromRight"},{"type":"text","text":": The modal window slides in from the right side of the screen."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWAnimationPresentFromLeft"},{"type":"text","text":": The modal window slides in from the left side of the screen."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWAnimationPresentNone"},{"text":": No animation is applied when presenting the modal window.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromBottom","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromTop","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentNone"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentNone":{"navigatorTitle":[{"text":"PWAnimationPresentNone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentNone","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentnone","role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentNone","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentNone"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/RawRepresentable-Implementations":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/RawRepresentable-Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromTop":{"type":"topic","navigatorTitle":[{"text":"PWAnimationPresentFromTop","kind":"identifier"}],"role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentFromTop","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromTop","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromtop","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWAnimationPresentFromTop","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromBottom":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromBottom","navigatorTitle":[{"text":"PWAnimationPresentFromBottom","kind":"identifier"}],"title":"PresentModalWindowAnimation.PWAnimationPresentFromBottom","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfrombottom","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromRight":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromRight","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWAnimationPresentFromRight"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromRight","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromright","title":"PresentModalWindowAnimation.PWAnimationPresentFromRight"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/init(rawValue:)":{"abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/Equatable-Implementations"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromLeft":{"navigatorTitle":[{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromleft","role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentFromLeft","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromLeft"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"PresentModalWindowAnimation","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromBottom","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromTop","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentNone"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentModalWindowAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentNone\/title","value":"PWAnimationPresentNone"},{"op":"replace","value":[{"text":"PWAnimationPresentNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentNone\/fragments"},{"value":"PresentModalWindowAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title"},{"value":[{"text":"PresentModalWindowAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromTop\/title","value":"PWAnimationPresentFromTop","op":"replace"},{"value":[{"text":"PWAnimationPresentFromTop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromTop\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromBottom\/title","op":"replace","value":"PWAnimationPresentFromBottom"},{"value":[{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromBottom\/fragments","op":"replace"},{"op":"replace","value":"PWAnimationPresentFromRight","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromRight\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromRight\/fragments","value":[{"kind":"identifier","text":"PWAnimationPresentFromRight"}],"op":"replace"},{"value":"PWAnimationPresentFromLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromLeft\/title","op":"replace"},{"value":[{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromLeft\/fragments"}]}]}