{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"PWJavaScriptInterface"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"type":"text","text":" "},{"type":"text","text":"to provide native calls and callbacks to Objective-C\/Swift."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewFinishLoad(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartClose(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartLoad(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWJavaScriptInterface","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Example:","type":"text"}]},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"(void)nativeCall:(NSString*)str :(PWJavaScriptCallback*)callback {"},{"text":" ","type":"text"},{"type":"text","text":"[callback executeWithParam:str];"},{"text":" ","type":"text"},{"type":"text","text":"}"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"…"}]},{"inlineContent":[{"text":"[[PWInAppManager sharedManager] addJavascriptInterface:[JavaScriptInterface new] withName:@“ObjC”];","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"JavaScript:"}]},{"type":"paragraph","inlineContent":[{"text":"ObjC.nativeCall(“exampleString”, function(str) {","type":"text"},{"type":"text","text":" "},{"type":"text","text":"console.log(str);"},{"text":" ","type":"text"},{"text":"});","type":"text"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Protocol","externalID":"c:objc(pl)PWJavaScriptInterface","title":"PWJavaScriptInterface","navigatorTitle":[{"kind":"identifier","text":"PWJavaScriptInterface"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWJavaScriptInterface"}],"symbolKind":"protocol","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewStartLoad(_:)":{"kind":"symbol","title":"onWebViewStartLoad(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartLoad(_:)","role":"symbol","navigatorTitle":[{"text":"onWebViewStartLoad:","kind":"identifier"}],"required":true,"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartload(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onWebViewStartLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"abstract":[{"text":"Tells the delegate that In-App Message load stated","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewFinishLoad(_:)":{"kind":"symbol","title":"onWebViewFinishLoad(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewFinishLoad(_:)","role":"symbol","navigatorTitle":[{"text":"onWebViewFinishLoad:","kind":"identifier"}],"required":true,"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewfinishload(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWebViewFinishLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that In-App Message load finished"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","abstract":[{"code":"PWJavaScriptInterface","type":"codeVoice"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"text":" ","type":"text"},{"text":"to provide native calls and callbacks to Objective-C\/Swift.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface","navigatorTitle":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"kind":"symbol","title":"PWJavaScriptInterface","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWJavaScriptInterface","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewStartClose(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartClose(_:)","abstract":[{"type":"text","text":"Tells the delegate that In-App Message is closing"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartclose(_:)","navigatorTitle":[{"kind":"identifier","text":"onWebViewStartClose:"}],"kind":"symbol","title":"onWebViewStartClose(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWebViewStartClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":"!)","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PWJavaScriptInterface","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWJavaScriptInterface","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PWJavaScriptInterface","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewFinishLoad(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartClose(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartLoad(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWJavaScriptInterface"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"onWebViewStartLoad:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartLoad(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onWebViewStartLoad:","kind":"identifier"}],"op":"replace"},{"value":"onWebViewFinishLoad:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewFinishLoad(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewFinishLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onWebViewFinishLoad:","kind":"identifier"}]},{"value":"PWJavaScriptInterface","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PWJavaScriptInterface"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartClose(_:)\/title","value":"onWebViewStartClose:"},{"value":[{"kind":"text","text":"- "},{"text":"onWebViewStartClose:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartClose(_:)\/fragments"}]}]}