{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"externalID":"c:PWRichMediaStyle.h@T@PWRichMediaLoadingViewBlock","title":"PWRichMediaLoadingViewBlock","symbolKind":"typealias","role":"symbol","roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmedialoadingviewblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwrichmedialoadingviewblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaLoadingViewBlock"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"},{"text":" = () -> ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView","text":"PWLoadingView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWLoadingView"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView":{"abstract":[],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwloadingview","title":"PWLoadingView","type":"topic","role":"symbol","navigatorTitle":[{"text":"PWLoadingView","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWLoadingView"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaLoadingViewBlock":{"type":"topic","navigatorTitle":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"abstract":[],"title":"PWRichMediaLoadingViewBlock","url":"\/documentation\/pushwooshframework\/pwrichmedialoadingviewblock","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaLoadingViewBlock"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","value":"PWRichMediaLoadingViewBlock","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaLoadingViewBlock"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BF*$objc(cs)PWLoadingView()","text":"PWLoadingView *(^)(void)"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWRichMediaLoadingViewBlock"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/title","value":"PWLoadingView"},{"value":[{"kind":"identifier","text":"PWLoadingView"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaLoadingViewBlock\/title","value":"PWRichMediaLoadingViewBlock","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaLoadingViewBlock\/fragments","value":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}