{"abstract":[{"type":"text","text":"Invokes callback with one argument"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParam:)"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute(withparam:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute(withparam:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"execute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withParam","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"param"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"execute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"executeWithParam:"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","role":"symbol","title":"execute(withParam:)","externalID":"c:objc(cs)PWJavaScriptCallback(im)executeWithParam:","symbolKind":"method"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback/execute(withParam:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute(withparam:)","abstract":[{"type":"text","text":"Invokes callback with one argument"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"execute"},{"text":"(","kind":"text"},{"text":"withParam","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!) -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"type":"topic","title":"execute(withParam:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParam:)","navigatorTitle":[{"text":"executeWithParam:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback","navigatorTitle":[{"text":"PWJavaScriptCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWJavaScriptCallback"}],"kind":"symbol","role":"symbol","title":"PWJavaScriptCallback","abstract":[{"code":"PWJavaScriptCallback","type":"codeVoice"},{"text":" is a representation of Javascript function","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"executeWithParam:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"executeWithParam:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"executeWithParam:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"param"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"executeWithParam:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParam:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParam:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"executeWithParam:"}],"op":"replace"},{"op":"replace","value":"PWJavaScriptCallback","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback\/fragments","value":[{"kind":"identifier","text":"PWJavaScriptCallback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}