{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMediaManager","kind":"typeIdentifier","text":"PWRichMediaManager"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"presentingDidFailFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": (any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"kind":"identifier","text":"richMediaManager:presentingDidFailForRichMedia:withError:"}],"role":"symbol","roleHeading":"Instance Method","required":true,"title":"richMediaManager(_:presentingDidFailFor:withError:)","symbolKind":"method","externalID":"c:objc(pl)PWRichMediaPresentingDelegate(im)richMediaManager:presentingDidFailForRichMedia:withError:","modules":[{"name":"PushwooshFramework"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"richMediaManager"},{"text":": ","kind":"text"},{"text":"PWRichMediaManager","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"presentingDidFailFor"},{"text":" ","kind":"text"},{"text":"richMedia","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia","text":"PWRichMedia","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:presentingdidfailfor:witherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:presentingdidfailfor:witherror:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:presentingDidFailFor:withError:)","interfaceLanguage":"swift"},"abstract":[{"text":"Tells the delegate that error during Rich Media presenting has been occured.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:presentingDidFailFor:withError:)":{"url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:presentingdidfailfor:witherror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"presentingDidFailFor"},{"text":": ","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withError"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:presentingDidFailFor:withError:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"richMediaManager:presentingDidFailForRichMedia:withError:"}],"title":"richMediaManager(_:presentingDidFailFor:withError:)","role":"symbol","required":true,"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that error during Rich Media presenting has been occured."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"richMediaManager:presentingDidFailForRichMedia:withError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:presentingDidFailForRichMedia:withError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"richMediaManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PWRichMediaManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","text":"PWRichMediaManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"richMediaManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"presentingDidFailForRichMedia:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","text":"PWRichMedia"},{"text":" *) ","kind":"text"},{"text":"richMedia","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PWRichMedia","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments","value":[{"text":"PWRichMedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:presentingDidFailFor:withError:)\/title","value":"richMediaManager:presentingDidFailForRichMedia:withError:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:presentingDidFailFor:withError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:presentingDidFailForRichMedia:withError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title","value":"PWRichMediaPresentingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}]},{"value":"PWRichMediaManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PWRichMediaManager"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments"}]}]}