{"metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"richMediaManager(_:shouldPresent:)","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"kind":"text","text":"("},{"text":"PWRichMediaManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"shouldPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia","text":"PWRichMedia"},{"text":"!) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"richMediaManager:shouldPresentRichMedia:"}],"externalID":"c:objc(pl)PWRichMediaPresentingDelegate(im)richMediaManager:shouldPresentRichMedia:","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:shouldPresent:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Checks the delegate whether the Rich Media should be displayed.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMediaManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"richMediaManager"},{"kind":"text","text":": "},{"text":"PWRichMediaManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"shouldPresent"},{"text":" ","kind":"text"},{"text":"richMedia","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:shouldpresent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:shouldpresent:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:shouldPresent:)":{"abstract":[{"text":"Checks the delegate whether the Rich Media should be displayed.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:shouldPresent:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"shouldPresent"},{"text":": ","kind":"text"},{"text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"richMediaManager:shouldPresentRichMedia:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:shouldpresent:)","title":"richMediaManager(_:shouldPresent:)","required":true,"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"richMediaManager:shouldPresentRichMedia:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"richMediaManager:shouldPresentRichMedia:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"richMediaManager:"},{"kind":"text","text":"("},{"text":"PWRichMediaManager","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"kind":"text","text":" *) "},{"text":"richMediaManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldPresentRichMedia:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"richMedia"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title","op":"replace","value":"PWRichMediaManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments","value":[{"kind":"identifier","text":"PWRichMediaManager"}]},{"op":"replace","value":"PWRichMediaPresentingDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title"},{"op":"replace","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title","value":"PWRichMedia"},{"value":[{"text":"PWRichMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:shouldPresent:)\/title","value":"richMediaManager:shouldPresentRichMedia:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:shouldPresent:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"richMediaManager:shouldPresentRichMedia:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}