{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Presents the modal window with the specified rich media content."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/presentModalWindow(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentModalWindow","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"richMedia"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","kind":"typeIdentifier","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The rich media content that will be displayed inside the modal window.","type":"text"}]}],"name":"richMedia"}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/presentmodalwindow(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/presentmodalwindow(_:)"]}],"metadata":{"roleHeading":"Instance Method","title":"presentModalWindow(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentModalWindow"},{"kind":"text","text":"("},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":")"}],"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"presentModalWindow:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)PWModalWindowConfiguration(im)presentModalWindow:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/presentModalWindow(_:)":{"role":"symbol","title":"presentModalWindow(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/presentModalWindow(_:)","kind":"symbol","navigatorTitle":[{"text":"presentModalWindow:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/presentmodalwindow(_:)","abstract":[{"text":"Presents the modal window with the specified rich media content.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentModalWindow"},{"text":"(","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"presentModalWindow:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentModalWindow:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"presentModalWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"richMedia"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"presentModalWindow:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1presentModalWindow(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1presentModalWindow(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentModalWindow:"}]},{"value":"PWModalWindowConfiguration","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}]},{"op":"replace","value":"PWRichMedia","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title"},{"value":[{"text":"PWRichMedia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments"}]}]}