{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/inApp","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediasource\/inapp"]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediasource\/inapp"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inApp","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"codeListing","syntax":null,"code":[" RichMedia is presented from In-App."]}],"kind":"content"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inApp"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}],"symbolKind":"case","title":"PWRichMediaSource.inApp","externalID":"c:@E@PWRichMediaSource@PWRichMediaSourceInApp","modules":[{"name":"PushwooshFramework"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/inApp":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inApp","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource\/inapp","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/inApp","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}],"role":"symbol","type":"topic","title":"PWRichMediaSource.inApp","kind":"symbol","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSource"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource","title":"PWRichMediaSource","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PWRichMediaSourceInApp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1inApp\/title","value":"PWRichMediaSourceInApp"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1inApp\/fragments","value":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/title","op":"replace","value":"PWRichMediaSource"},{"value":[{"kind":"identifier","text":"PWRichMediaSource"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}