{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromTop","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromTop","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PWAnimationPresentFromTop"}],"externalID":"c:@E@PresentModalWindowAnimation@PWAnimationPresentFromTop","role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentFromTop","roleHeading":"Case","symbolKind":"case","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationPresentFromTop","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromtop"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromtop"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromTop":{"type":"topic","navigatorTitle":[{"text":"PWAnimationPresentFromTop","kind":"identifier"}],"role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentFromTop","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromTop","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromtop","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWAnimationPresentFromTop","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PWAnimationPresentFromTop","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PWAnimationPresentFromTop"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"PWAnimationPresentFromTop"}]}]}},{"value":"PWAnimationPresentFromTop","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromTop\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromTop\/fragments","value":[{"text":"PWAnimationPresentFromTop","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title","value":"PresentModalWindowAnimation","op":"replace"},{"value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments"}]}]}