{"sections":[],"metadata":{"navigatorTitle":[{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@PresentModalWindowAnimation@PWAnimationPresentFromLeft","modules":[{"name":"PushwooshFramework"}],"title":"PresentModalWindowAnimation.PWAnimationPresentFromLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationPresentFromLeft"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromLeft","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromleft"]},{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromleft"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromLeft":{"navigatorTitle":[{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromleft","role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentFromLeft","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromLeft"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWAnimationPresentFromLeft","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PWAnimationPresentFromLeft","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWAnimationPresentFromLeft"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PWAnimationPresentFromLeft","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromLeft\/title"},{"value":[{"kind":"identifier","text":"PWAnimationPresentFromLeft"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromLeft\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title","value":"PresentModalWindowAnimation","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments","op":"replace","value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}