{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWHapticFeedbackHard","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"text":"PWHapticFeedbackHard","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@HapticFeedbackType@PWHapticFeedbackHard","title":"HapticFeedbackType.PWHapticFeedbackHard","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackhard"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackhard"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWHapticFeedbackHard","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackHard"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype","abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"kind":"symbol","title":"HapticFeedbackType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticFeedbackType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HapticFeedbackType"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackHard":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackHard","title":"HapticFeedbackType.PWHapticFeedbackHard","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackhard","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackHard"}],"navigatorTitle":[{"kind":"identifier","text":"PWHapticFeedbackHard"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PWHapticFeedbackHard"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWHapticFeedbackHard","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"PWHapticFeedbackHard","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"HapticFeedbackType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/fragments","value":[{"kind":"identifier","text":"HapticFeedbackType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackHard\/title","value":"PWHapticFeedbackHard"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackHard\/fragments","value":[{"text":"PWHapticFeedbackHard","kind":"identifier"}],"op":"replace"}]}]}