{"sections":[],"abstract":[{"type":"text","text":"Vibration is off by default."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWHapticFeedbackNone"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbacknone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbacknone"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackNone"},"metadata":{"navigatorTitle":[{"text":"PWHapticFeedbackNone","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"PushwooshFramework"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackNone"}],"externalID":"c:@E@HapticFeedbackType@PWHapticFeedbackNone","title":"HapticFeedbackType.PWHapticFeedbackNone","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType"]]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype","abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"kind":"symbol","title":"HapticFeedbackType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticFeedbackType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HapticFeedbackType"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackNone":{"kind":"symbol","abstract":[{"type":"text","text":"Vibration is off by default."}],"navigatorTitle":[{"kind":"identifier","text":"PWHapticFeedbackNone"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackNone","type":"topic","role":"symbol","title":"HapticFeedbackType.PWHapticFeedbackNone","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbacknone","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWHapticFeedbackNone","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PWHapticFeedbackNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWHapticFeedbackNone"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PWHapticFeedbackNone","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/title","op":"replace","value":"HapticFeedbackType"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/fragments","value":[{"kind":"identifier","text":"HapticFeedbackType"}],"op":"replace"},{"value":"PWHapticFeedbackNone","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackNone\/title"},{"op":"replace","value":[{"text":"PWHapticFeedbackNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackNone\/fragments"}]}]}