{"metadata":{"externalID":"c:@E@PresentModalWindowAnimation@PWAnimationPresentNone","title":"PresentModalWindowAnimation.PWAnimationPresentNone","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationPresentNone"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PWAnimationPresentNone"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentNone"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationPresentNone"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentnone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentnone"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentNone":{"navigatorTitle":[{"text":"PWAnimationPresentNone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentNone","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentnone","role":"symbol","title":"PresentModalWindowAnimation.PWAnimationPresentNone","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentNone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"PWAnimationPresentNone","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"PWAnimationPresentNone","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PWAnimationPresentNone","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PresentModalWindowAnimation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title","op":"replace"},{"value":[{"text":"PresentModalWindowAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentNone\/title","value":"PWAnimationPresentNone"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentNone\/fragments","op":"replace","value":[{"text":"PWAnimationPresentNone","kind":"identifier"}]}]}]}