{"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromRight","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWAnimationPresentFromRight"}],"roleHeading":"Case","title":"PresentModalWindowAnimation.PWAnimationPresentFromRight","externalID":"c:@E@PresentModalWindowAnimation@PWAnimationPresentFromRight"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromright"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationPresentFromRight"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromRight","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromRight":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWAnimationPresentFromRight","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWAnimationPresentFromRight"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromRight","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfromright","title":"PresentModalWindowAnimation.PWAnimationPresentFromRight"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"PWAnimationPresentFromRight","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"PWAnimationPresentFromRight","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PWAnimationPresentFromRight","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromRight\/title","value":"PWAnimationPresentFromRight"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromRight\/fragments","value":[{"kind":"identifier","text":"PWAnimationPresentFromRight"}]},{"value":"PresentModalWindowAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments","value":[{"text":"PresentModalWindowAnimation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}