{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/isCommunicationEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCommunicationEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/iscommunicationenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/iscommunicationenabled"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"communicationEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isCommunicationEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","externalID":"c:objc(cs)PWGDPRManager(py)communicationEnabled","symbolKind":"property","title":"isCommunicationEnabled","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager"]]},"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager","title":"PWGDPRManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWGDPRManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWGDPRManager"}],"url":"\/documentation\/pushwooshframework\/pwgdprmanager","abstract":[],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager/isCommunicationEnabled":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/isCommunicationEnabled","title":"isCommunicationEnabled","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCommunicationEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"communicationEnabled","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwgdprmanager\/iscommunicationenabled","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"communicationEnabled","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"communicationEnabled","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":", "},{"text":"getter","kind":"keyword"},{"kind":"text","text":"="},{"kind":"identifier","text":"isCommunicationEnabled"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"communicationEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PWGDPRManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/fragments","value":[{"kind":"identifier","text":"PWGDPRManager"}],"op":"replace"},{"op":"replace","value":"communicationEnabled","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1isCommunicationEnabled\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1isCommunicationEnabled\/fragments","op":"replace","value":[{"text":"communicationEnabled","kind":"identifier"}]}]}]}