{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprdeletionui()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprdeletionui()"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/showGDPRDeletionUI()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showGDPRDeletionUI","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showGDPRDeletionUI","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"showGDPRDeletionUI"}],"title":"showGDPRDeletionUI()","externalID":"c:objc(cs)PWGDPRManager(im)showGDPRDeletionUI","role":"symbol","modules":[{"name":"PushwooshFramework"}]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager/showGDPRDeletionUI()":{"url":"\/documentation\/pushwooshframework\/pwgdprmanager\/showgdprdeletionui()","role":"symbol","navigatorTitle":[{"text":"showGDPRDeletionUI","kind":"identifier"}],"title":"showGDPRDeletionUI()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/showGDPRDeletionUI()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showGDPRDeletionUI","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager","title":"PWGDPRManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWGDPRManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWGDPRManager"}],"url":"\/documentation\/pushwooshframework\/pwgdprmanager","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"showGDPRDeletionUI","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showGDPRDeletionUI"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showGDPRDeletionUI"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"showGDPRDeletionUI","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1showGDPRDeletionUI()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1showGDPRDeletionUI()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showGDPRDeletionUI"}]},{"op":"replace","value":"PWGDPRManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/title"},{"value":[{"kind":"identifier","text":"PWGDPRManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/fragments","op":"replace"}]}]}