{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"extendedModule":"Foundation","roleHeading":"Type Property","title":"PWGDPRStatusDidChange","role":"symbol","externalID":"c:@PWGDPRStatusDidChangeNotification","modules":[{"name":"PushwooshFramework","relatedModules":["Foundation"]}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWGDPRStatusDidChange"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"PWGDPRStatusDidChangeNotification","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwgdprstatusdidchange"]},{"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwgdprstatusdidchange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWGDPRStatusDidChange","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWGDPRStatusDidChange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"languages":["swift"]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation":{"type":"topic","url":"\/documentation\/pushwooshframework\/foundation","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","abstract":[],"title":"Foundation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification":{"navigatorTitle":[{"text":"NSNotification","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification","abstract":[],"title":"NSNotification"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name/PWGDPRStatusDidChange":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWGDPRStatusDidChange","title":"PWGDPRStatusDidChange","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwgdprstatusdidchange","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWGDPRStatusDidChange","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"navigatorTitle":[{"text":"PWGDPRStatusDidChangeNotification","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name":{"navigatorTitle":[{"text":"Name","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"text":"Name","kind":"identifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"NSNotification.Name"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PWGDPRStatusDidChangeNotification"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PWGDPRStatusDidChangeNotification","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWGDPRStatusDidChangeNotification"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWGDPRStatusDidChange\/title","op":"replace","value":"PWGDPRStatusDidChangeNotification"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWGDPRStatusDidChange\/fragments","value":[{"text":"PWGDPRStatusDidChangeNotification","kind":"identifier"}],"op":"replace"}]}]}