{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissLeft"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection"]]},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWSwipeDismissLeft","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissLeft"}],"symbolKind":"case","externalID":"c:@E@DismissSwipeDirection@PWSwipeDismissLeft","title":"DismissSwipeDirection.PWSwipeDismissLeft","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissLeft"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissleft"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissLeft":{"navigatorTitle":[{"text":"PWSwipeDismissLeft","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissleft","title":"DismissSwipeDirection.PWSwipeDismissLeft","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissLeft"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissLeft"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection":{"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissSwipeDirection"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection","title":"DismissSwipeDirection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PWSwipeDismissLeft","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"PWSwipeDismissLeft"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PWSwipeDismissLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissLeft\/title","value":"PWSwipeDismissLeft"},{"value":[{"kind":"identifier","text":"PWSwipeDismissLeft"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissLeft\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/title","value":"DismissSwipeDirection"},{"value":[{"kind":"identifier","text":"DismissSwipeDirection"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}