{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackMedium","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWHapticFeedbackMedium","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"PWHapticFeedbackMedium","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWHapticFeedbackMedium","kind":"identifier"}],"role":"symbol","externalID":"c:@E@HapticFeedbackType@PWHapticFeedbackMedium","title":"HapticFeedbackType.PWHapticFeedbackMedium","roleHeading":"Case","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackmedium"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackmedium"]}],"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype","abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"kind":"symbol","title":"HapticFeedbackType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticFeedbackType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HapticFeedbackType"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType/PWHapticFeedbackMedium":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType\/PWHapticFeedbackMedium","title":"HapticFeedbackType.PWHapticFeedbackMedium","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype\/pwhapticfeedbackmedium","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWHapticFeedbackMedium"}],"navigatorTitle":[{"text":"PWHapticFeedbackMedium","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"PWHapticFeedbackMedium","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PWHapticFeedbackMedium","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PWHapticFeedbackMedium"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"HapticFeedbackType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/title","op":"replace"},{"op":"replace","value":[{"text":"HapticFeedbackType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/fragments"},{"value":"PWHapticFeedbackMedium","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackMedium\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType~1PWHapticFeedbackMedium\/fragments","value":[{"kind":"identifier","text":"PWHapticFeedbackMedium"}]}]}]}