{"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWInlineInAppViewDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"symbolKind":"protocol","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(pl)PWInlineInAppViewDelegate","navigatorTitle":[{"text":"PWInlineInAppViewDelegate","kind":"identifier"}],"title":"PWInlineInAppViewDelegate","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didChangeSizeOfInline(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didCloseInline(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/inlineInAppDidLoad(in:)"]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate","title":"PWInlineInAppViewDelegate","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/didChangeSizeOfInline(_:)":{"type":"topic","kind":"symbol","title":"didChangeSizeOfInline(_:)","required":true,"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didchangesizeofinline(_:)","abstract":[],"navigatorTitle":[{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didChangeSizeOfInline(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didChangeSizeOfInline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"kind":"text","text":"!)"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/inlineInAppDidLoad(in:)":{"kind":"symbol","type":"topic","title":"inlineInAppDidLoad(in:)","required":true,"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/inlineinappdidload(in:)","abstract":[],"navigatorTitle":[{"text":"inlineInAppDidLoadInView:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/inlineInAppDidLoad(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"inlineInAppDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"text":"!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/didCloseInline(_:)":{"abstract":[],"required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didcloseinline(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didCloseInline","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PWInlineInAppView","kind":"typeIdentifier","text":"PWInlineInAppView"},{"text":"!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didCloseInline(_:)","navigatorTitle":[{"kind":"identifier","text":"didCloseInlineInAppView:"}],"title":"didCloseInline(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWInlineInAppViewDelegate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PWInlineInAppViewDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didChangeSizeOfInline(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didCloseInline(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/inlineInAppDidLoad(in:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"PWInlineInAppViewDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PWInlineInAppViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/title"},{"op":"replace","value":[{"text":"PWInlineInAppViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didChangeSizeOfInline(_:)\/title","value":"didChangeSizeOfInlineInAppView:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didChangeSizeOfInline(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"inlineInAppDidLoadInView:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1inlineInAppDidLoad(in:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1inlineInAppDidLoad(in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"inlineInAppDidLoadInView:","kind":"identifier"}]},{"op":"replace","value":"didCloseInlineInAppView:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didCloseInline(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didCloseInline(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCloseInlineInAppView:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}