{"abstract":[{"type":"text","text":"Interface for Rich Media presentation managing."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didClose:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didPresent:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:presentingDidFailFor:withError:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:shouldPresent:)"]}],"sections":[],"metadata":{"externalID":"c:objc(pl)PWRichMediaPresentingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"symbolKind":"protocol","title":"PWRichMediaPresentingDelegate","role":"symbol","roleHeading":"Protocol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:presentingDidFailFor:withError:)":{"url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:presentingdidfailfor:witherror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"presentingDidFailFor"},{"text":": ","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withError"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:presentingDidFailFor:withError:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"richMediaManager:presentingDidFailForRichMedia:withError:"}],"title":"richMediaManager(_:presentingDidFailFor:withError:)","role":"symbol","required":true,"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that error during Rich Media presenting has been occured."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:shouldPresent:)":{"abstract":[{"text":"Checks the delegate whether the Rich Media should be displayed.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:shouldPresent:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"shouldPresent"},{"text":": ","kind":"text"},{"text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"richMediaManager:shouldPresentRichMedia:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:shouldpresent:)","title":"richMediaManager(_:shouldPresent:)","required":true,"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:didPresent:)":{"abstract":[{"type":"text","text":"Tells the delegate that Rich Media has been displayed."}],"navigatorTitle":[{"text":"richMediaManager:didPresentRichMedia:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didPresent:)","title":"richMediaManager(_:didPresent:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMediaManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"didPresent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia","text":"PWRichMedia"},{"text":"!)","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didpresent:)","type":"topic","kind":"symbol","required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:didClose:)":{"kind":"symbol","type":"topic","title":"richMediaManager(_:didClose:)","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didclose:)","role":"symbol","navigatorTitle":[{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didClose:)","abstract":[{"text":"Tells the delegate that Rich Media has been closed.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"text":"!, ","kind":"text"},{"text":"didClose","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":"!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PWRichMediaPresentingDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didClose:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didPresent:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:presentingDidFailFor:withError:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:shouldPresent:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"richMediaManager:presentingDidFailForRichMedia:withError:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:presentingDidFailFor:withError:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:presentingDidFailFor:withError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"richMediaManager:presentingDidFailForRichMedia:withError:"}]},{"value":"richMediaManager:shouldPresentRichMedia:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:shouldPresent:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:shouldPresent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:shouldPresentRichMedia:","kind":"identifier"}]},{"value":"richMediaManager:didPresentRichMedia:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didPresent:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didPresent:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:didPresentRichMedia:","kind":"identifier"}]},{"value":"richMediaManager:didCloseRichMedia:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didClose:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didClose:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title","value":"PWRichMediaPresentingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments","op":"replace","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}]}]}]}