{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager"]]},"abstract":[{"type":"text","text":"Delegate for Rich Media presentation managing."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","preciseIdentifier":"c:objc(pl)PWRichMediaPresentingDelegate","kind":"typeIdentifier","text":"PWRichMediaPresentingDelegate"},{"kind":"text","text":")! { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"property","title":"delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:objc(cs)PWRichMediaManager(py)delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"PWRichMediaPresentingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWRichMediaPresentingDelegate"},{"kind":"text","text":")!"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/delegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediamanager\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediamanager\/delegate"]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager/delegate":{"title":"delegate","kind":"symbol","abstract":[{"text":"Delegate for Rich Media presentation managing.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/delegate","url":"\/documentation\/pushwooshframework\/pwrichmediamanager\/delegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"PWRichMediaPresentingDelegate","preciseIdentifier":"c:objc(pl)PWRichMediaPresentingDelegate"},{"text":")!","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"delegate","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<PWRichMediaPresentingDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)PWRichMediaPresentingDelegate"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PWRichMediaManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments","value":[{"kind":"identifier","text":"PWRichMediaManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title","value":"PWRichMediaPresentingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1delegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}