{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInlineInAppViewDelegate","text":"PWInlineInAppViewDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate"},{"text":")! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/delegate","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinlineinappview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappview\/delegate"]}],"metadata":{"externalID":"c:objc(cs)PWInlineInAppView(py)delegate","modules":[{"name":"PushwooshFramework"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)PWInlineInAppViewDelegate","text":"PWInlineInAppViewDelegate","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView/delegate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)PWInlineInAppViewDelegate","kind":"typeIdentifier","text":"PWInlineInAppViewDelegate"},{"kind":"text","text":")!"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview\/delegate","title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/delegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate","title":"PWInlineInAppViewDelegate","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview","title":"PWInlineInAppView","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppView"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)PWInlineInAppViewDelegate","kind":"typeIdentifier","text":"id<PWInlineInAppViewDelegate>"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1delegate\/title","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1delegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/title","op":"replace","value":"PWInlineInAppViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/fragments","value":[{"text":"PWInlineInAppViewDelegate","kind":"identifier"}]},{"op":"replace","value":"PWInlineInAppView","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/fragments","value":[{"text":"PWInlineInAppView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}