{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"onWebViewFinishLoad:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","title":"onWebViewFinishLoad(_:)","role":"symbol","externalID":"c:objc(pl)PWJavaScriptInterface(im)onWebViewFinishLoad:","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onWebViewFinishLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":"!)","kind":"text"}],"platforms":[{"introducedAt":"8.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewFinishLoad(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onWebViewFinishLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":"!)"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewfinishload(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewfinishload(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that In-App Message load finished"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","abstract":[{"code":"PWJavaScriptInterface","type":"codeVoice"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"text":" ","type":"text"},{"text":"to provide native calls and callbacks to Objective-C\/Swift.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface","navigatorTitle":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"kind":"symbol","title":"PWJavaScriptInterface","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWJavaScriptInterface","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewFinishLoad(_:)":{"kind":"symbol","title":"onWebViewFinishLoad(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewFinishLoad(_:)","role":"symbol","navigatorTitle":[{"text":"onWebViewFinishLoad:","kind":"identifier"}],"required":true,"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewfinishload(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWebViewFinishLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that In-App Message load finished"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"onWebViewFinishLoad:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onWebViewFinishLoad:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onWebViewFinishLoad:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWJavaScriptInterface","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/title"},{"value":[{"kind":"identifier","text":"PWJavaScriptInterface"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/fragments"},{"value":"onWebViewFinishLoad:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewFinishLoad(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewFinishLoad(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onWebViewFinishLoad:","kind":"identifier"}],"op":"replace"}]}]}