{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"runPresentingAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"withContentView","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"contentView","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"!, ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")!)"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"required":true,"roleHeading":"Instance Method","externalID":"c:objc(pl)PWRichMediaStyleAnimationDelegate(im)runPresentingAnimationWithContentView:parentView:completion:","title":"runPresentingAnimation(withContentView:parentView:completion:)","navigatorTitle":[{"text":"runPresentingAnimationWithContentView:parentView:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"runPresentingAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withContentView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"platforms":[{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iOS","beta":false}],"symbolKind":"method","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate\/runpresentinganimation(withcontentview:parentview:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate\/runpresentinganimation(withcontentview:parentview:completion:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runPresentingAnimation(withContentView:parentView:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate":{"abstract":[{"text":"Interface for Rich Media Custom Animation.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate","navigatorTitle":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"title":"PWRichMediaStyleAnimationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate/runPresentingAnimation(withContentView:parentView:completion:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runPresentingAnimation(withContentView:parentView:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"runPresentingAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withContentView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"!, "},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"title":"runPresentingAnimation(withContentView:parentView:completion:)","navigatorTitle":[{"kind":"identifier","text":"runPresentingAnimationWithContentView:parentView:completion:"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate\/runpresentinganimation(withcontentview:parentview:completion:)","role":"symbol","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"runPresentingAnimationWithContentView:parentView:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runPresentingAnimationWithContentView:parentView:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"runPresentingAnimationWithContentView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" *) ","kind":"text"},{"text":"contentView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentView"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@dispatch_block_t","text":"dispatch_block_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/title","value":"PWRichMediaStyleAnimationDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWRichMediaStyleAnimationDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runPresentingAnimation(withContentView:parentView:completion:)\/title","value":"runPresentingAnimationWithContentView:parentView:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"runPresentingAnimationWithContentView:parentView:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runPresentingAnimation(withContentView:parentView:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}