{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartclose(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartclose(_:)"]}],"metadata":{"role":"symbol","title":"onWebViewStartClose(_:)","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onWebViewStartClose","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"onWebViewStartClose:","kind":"identifier"}],"externalID":"c:objc(pl)PWJavaScriptInterface(im)onWebViewStartClose:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartClose(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWebViewStartClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":"!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Tells the delegate that In-App Message is closing","type":"text"}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","abstract":[{"code":"PWJavaScriptInterface","type":"codeVoice"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"text":" ","type":"text"},{"text":"to provide native calls and callbacks to Objective-C\/Swift.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface","navigatorTitle":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"kind":"symbol","title":"PWJavaScriptInterface","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWJavaScriptInterface","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewStartClose(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartClose(_:)","abstract":[{"type":"text","text":"Tells the delegate that In-App Message is closing"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartclose(_:)","navigatorTitle":[{"kind":"identifier","text":"onWebViewStartClose:"}],"kind":"symbol","title":"onWebViewStartClose(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWebViewStartClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":"!)","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onWebViewStartClose:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onWebViewStartClose:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onWebViewStartClose:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWJavaScriptInterface","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/fragments","value":[{"text":"PWJavaScriptInterface","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartClose(_:)\/title","op":"replace","value":"onWebViewStartClose:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onWebViewStartClose:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartClose(_:)\/fragments","op":"replace"}]}]}