{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWCornerTypeBottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","text":"CornerType","preciseIdentifier":"c:@E@CornerType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomRight"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"PWCornerTypeBottomRight","kind":"identifier"}],"roleHeading":"Type Property","title":"PWCornerTypeBottomRight","modules":[{"name":"PushwooshFramework"}],"role":"symbol","externalID":"c:@E@CornerType@PWCornerTypeBottomRight","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWCornerTypeBottomRight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","kind":"typeIdentifier","text":"CornerType"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomright"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeBottomRight":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeBottomRight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","text":"CornerType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeBottomRight"}],"role":"symbol","abstract":[],"title":"PWCornerTypeBottomRight","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomRight","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomright"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PWCornerTypeBottomRight","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PWCornerTypeBottomRight","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PWCornerTypeBottomRight","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"PWCornerTypeBottomRight","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomRight\/fragments","value":[{"text":"PWCornerTypeBottomRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType","op":"replace"},{"value":[{"text":"CornerType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}