{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopRight","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","externalID":"c:@E@CornerType@PWCornerTypeTopRight","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWCornerTypeTopRight"},{"text":": ","kind":"text"},{"text":"CornerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType"}],"role":"symbol","title":"PWCornerTypeTopRight","symbolKind":"property","navigatorTitle":[{"text":"PWCornerTypeTopRight","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"PWCornerTypeTopRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CornerType","preciseIdentifier":"c:@E@CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopright"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeTopRight":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeTopRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType","text":"CornerType"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeTopRight"}],"role":"symbol","abstract":[],"title":"PWCornerTypeTopRight","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopRight","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopright"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PWCornerTypeTopRight","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWCornerTypeTopRight"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWCornerTypeTopRight"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments","value":[{"text":"CornerType","kind":"identifier"}],"op":"replace"},{"value":"PWCornerTypeTopRight","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopRight\/title","op":"replace"},{"value":[{"text":"PWCornerTypeTopRight","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopRight\/fragments","op":"replace"}]}]}