{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)PWGDPRManager(cm)sharedManager","title":"shared()","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/shared()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/shared()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwgdprmanager\/shared()"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager","title":"PWGDPRManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWGDPRManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWGDPRManager"}],"url":"\/documentation\/pushwooshframework\/pwgdprmanager","abstract":[],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWGDPRManager/shared()":{"role":"symbol","title":"shared()","type":"topic","url":"\/documentation\/pushwooshframework\/pwgdprmanager\/shared()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWGDPRManager\/shared()","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"sharedManager"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sharedManager","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sharedManager"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"sharedManager","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/title","value":"PWGDPRManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager\/fragments","value":[{"text":"PWGDPRManager","kind":"identifier"}]},{"value":"sharedManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1shared()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWGDPRManager~1shared()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sharedManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}