{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionDefault"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionDefault","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","title":"ModalWindowPosition.PWModalWindowPositionDefault","role":"symbol","externalID":"c:@E@ModalWindowPosition@PWModalWindowPositionDefault","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionDefault","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"PWModalWindowPositionDefault","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiondefault"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiondefault"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionDefault":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionDefault","title":"ModalWindowPosition.PWModalWindowPositionDefault","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiondefault","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionDefault","kind":"identifier"}],"navigatorTitle":[{"text":"PWModalWindowPositionDefault","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"PWModalWindowPositionDefault","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWModalWindowPositionDefault"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWModalWindowPositionDefault"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"PWModalWindowPositionDefault","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionDefault\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionDefault\/fragments","value":[{"kind":"identifier","text":"PWModalWindowPositionDefault"}],"op":"replace"},{"op":"replace","value":"ModalWindowPosition","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title"},{"value":[{"text":"ModalWindowPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments"}]}]}