{"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)PWModalWindowConfiguration(im)configureModalWindowWith:presentAnimation:dismissAnimation:","title":"configureModalWindow(with:present:dismiss:)","navigatorTitle":[{"text":"configureModalWindowWith:presentAnimation:dismissAnimation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureModalWindow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"ModalWindowPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@ModalWindowPosition"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"present"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@PresentModalWindowAnimation","text":"PresentModalWindowAnimation"},{"text":", ","kind":"text"},{"text":"dismiss","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@DismissModalWindowAnimation","text":"DismissModalWindowAnimation"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","abstract":[{"text":"Configures the modal window to be displayed at a specified position on the screen and defines the animation styles for presenting and dismissing the window.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureModalWindow"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"position","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@ModalWindowPosition","text":"ModalWindowPosition"},{"text":", ","kind":"text"},{"text":"present","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"presentAnimation","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PresentModalWindowAnimation","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@E@PresentModalWindowAnimation"},{"text":", ","kind":"text"},{"text":"dismiss","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dismissAnimation","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","preciseIdentifier":"c:@E@DismissModalWindowAnimation","text":"DismissModalWindowAnimation"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"text":"The screen position where the modal window will be displayed (e.g., top, bottom).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The animation style used when the modal window is presented (e.g., fade, slide).","type":"text"}]}],"name":"presentAnimation"},{"content":[{"inlineContent":[{"type":"text","text":"The animation style used when the modal window is dismissed (e.g., fade, slide)."}],"type":"paragraph"}],"name":"dismissAnimation"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/configuremodalwindow(with:present:dismiss:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/configuremodalwindow(with:present:dismiss:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/configureModalWindow(with:present:dismiss:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/configureModalWindow(with:present:dismiss:)":{"role":"symbol","title":"configureModalWindow(with:present:dismiss:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/configureModalWindow(with:present:dismiss:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureModalWindowWith:presentAnimation:dismissAnimation:"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/configuremodalwindow(with:present:dismiss:)","abstract":[{"type":"text","text":"Configures the modal window to be displayed at a specified position on the screen and defines the animation styles for presenting and dismissing the window."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureModalWindow"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ModalWindowPosition","text":"ModalWindowPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"present"},{"text":": ","kind":"text"},{"text":"PresentModalWindowAnimation","preciseIdentifier":"c:@E@PresentModalWindowAnimation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismiss","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@DismissModalWindowAnimation","text":"DismissModalWindowAnimation","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"configureModalWindowWith:presentAnimation:dismissAnimation:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureModalWindowWith:presentAnimation:dismissAnimation:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"configureModalWindowWith:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@ModalWindowPosition","text":"ModalWindowPosition"},{"kind":"text","text":") "},{"text":"position","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"presentAnimation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PresentModalWindowAnimation","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@E@PresentModalWindowAnimation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"presentAnimation"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAnimation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DismissModalWindowAnimation","preciseIdentifier":"c:@E@DismissModalWindowAnimation","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"},{"kind":"text","text":") "},{"text":"dismissAnimation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PresentModalWindowAnimation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments","value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title","value":"PWModalWindowConfiguration"},{"value":[{"text":"PWModalWindowConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments","op":"replace"},{"value":"DismissModalWindowAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title"},{"value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1configureModalWindow(with:present:dismiss:)\/title","value":"configureModalWindowWith:presentAnimation:dismissAnimation:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"configureModalWindowWith:presentAnimation:dismissAnimation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1configureModalWindow(with:present:dismiss:)\/fragments"},{"value":"ModalWindowPosition","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title"},{"value":[{"text":"ModalWindowPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}