{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CornerType","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWCornerTypeNone"},{"text":": No corners are rounded.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWCornerTypeTopLeft"},{"text":": The top-left corner is rounded.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWCornerTypeTopRight"},{"type":"text","text":": The top-right corner is rounded."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PWCornerTypeBottomLeft"},{"text":": The bottom-left corner is rounded.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWCornerTypeBottomRight"},{"text":": The bottom-right corner is rounded.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"In Objective-C, multiple values can be combined using the bitwise OR operator (","type":"text"},{"code":"|","type":"codeVoice"},{"type":"text","text":")."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift, you can use the "},{"type":"codeVoice","code":"OptionSet"},{"text":" syntax to combine multiple corner types. For example:","type":"text"}]},{"code":["let cornerTypes: CornerType = [.topLeft, .bottomRight]",""],"type":"codeListing","syntax":"swift"}]}],"abstract":[{"type":"text","text":"Enum options defining the corners that can be rounded in a modal window."}],"metadata":{"title":"CornerType","role":"symbol","externalID":"c:@E@CornerType","symbolKind":"struct","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Structure","navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CornerType"}]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopRight"],"title":"Type Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/OptionSet-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/SetAlgebra-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/s25ExpressibleByArrayLiteralP","doc:\/\/com.pushwoosh.PushwooshiOS\/s9OptionSetP","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshiOS\/s10SetAlgebraP"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/cornertype"]},{"paths":["\/documentation\/pushwooshframework\/cornertype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/init(rawValue:)","url":"\/documentation\/pushwooshframework\/cornertype\/init(rawvalue:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeTopRight":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeTopRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType","text":"CornerType"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeTopRight"}],"role":"symbol","abstract":[],"title":"PWCornerTypeTopRight","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopRight","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopright"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeBottomRight":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeBottomRight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","text":"CornerType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeBottomRight"}],"role":"symbol","abstract":[],"title":"PWCornerTypeBottomRight","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomRight","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomright"},"doc://com.pushwoosh.PushwooshiOS/s10SetAlgebraP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s10SetAlgebraP","title":"Swift.SetAlgebra","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/OptionSet-Implementations":{"abstract":[],"kind":"article","type":"topic","url":"\/documentation\/pushwooshframework\/cornertype\/optionset-implementations","title":"OptionSet Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/OptionSet-Implementations","role":"collectionGroup"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeNone":{"type":"topic","fragments":[{"kind":"identifier","text":"PWCornerTypeNone"}],"role":"symbol","abstract":[],"title":"PWCornerTypeNone","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeNone","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypenone"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/SetAlgebra-Implementations":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/SetAlgebra-Implementations","kind":"article","abstract":[],"url":"\/documentation\/pushwooshframework\/cornertype\/setalgebra-implementations","type":"topic","title":"SetAlgebra Implementations","role":"collectionGroup"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/s9OptionSetP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s9OptionSetP","title":"Swift.OptionSet","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeBottomLeft":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeBottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType","text":"CornerType"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeBottomLeft"}],"role":"symbol","abstract":[],"title":"PWCornerTypeBottomLeft","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomLeft","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomleft"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s25ExpressibleByArrayLiteralP","type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/Equatable-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/Equatable-Implementations","url":"\/documentation\/pushwooshframework\/cornertype\/equatable-implementations"},"doc://com.pushwoosh.PushwooshiOS/SY":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeTopLeft":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeTopLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","text":"CornerType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeTopLeft"}],"role":"symbol","abstract":[],"title":"PWCornerTypeTopLeft","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopLeft","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopleft"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"CornerType","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CornerType"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"CornerType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeNone","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopRight"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PWCornerTypeTopRight","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopRight\/title"},{"value":[{"text":"PWCornerTypeTopRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopRight\/fragments"},{"value":"PWCornerTypeBottomRight","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomRight\/fragments","value":[{"kind":"identifier","text":"PWCornerTypeBottomRight"}]},{"value":"PWCornerTypeBottomLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomLeft\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomLeft\/fragments","value":[{"text":"PWCornerTypeBottomLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments","value":[{"text":"CornerType","kind":"identifier"}]},{"value":"PWCornerTypeTopLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopLeft\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopLeft\/fragments","op":"replace","value":[{"text":"PWCornerTypeTopLeft","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}