{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissSwipeDirection","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissDown","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissNone","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissUp"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection"]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"symbolKind":"enum","externalID":"c:@E@DismissSwipeDirection","role":"symbol","title":"DismissSwipeDirection","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DismissSwipeDirection","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/init(rawValue:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/init(rawValue:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissLeft":{"navigatorTitle":[{"text":"PWSwipeDismissLeft","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissleft","title":"DismissSwipeDirection.PWSwipeDismissLeft","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissLeft"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissLeft"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissRight":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissRight"}],"navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissRight"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissright","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissRight","title":"DismissSwipeDirection.PWSwipeDismissRight"},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection":{"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissSwipeDirection"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection","title":"DismissSwipeDirection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissUp":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissUp"}],"navigatorTitle":[{"text":"PWSwipeDismissUp","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissup","abstract":[],"title":"DismissSwipeDirection.PWSwipeDismissUp","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissUp","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/RawRepresentable-Implementations":{"url":"\/documentation\/pushwooshframework\/dismissswipedirection\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/RawRepresentable-Implementations"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissDown":{"navigatorTitle":[{"text":"PWSwipeDismissDown","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissdown","title":"DismissSwipeDirection.PWSwipeDismissDown","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWSwipeDismissDown","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissDown"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/equatable-implementations","title":"Equatable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/Equatable-Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissNone":{"navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissNone"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissNone","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWSwipeDismissNone","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissnone","title":"DismissSwipeDirection.PWSwipeDismissNone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DismissSwipeDirection"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DismissSwipeDirection","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DismissSwipeDirection"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissDown","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissLeft","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissNone","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissRight","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissUp"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DismissSwipeDirection"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"PWSwipeDismissLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissLeft\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissLeft\/fragments","value":[{"text":"PWSwipeDismissLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissRight\/title","value":"PWSwipeDismissRight","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissRight\/fragments","value":[{"text":"PWSwipeDismissRight","kind":"identifier"}],"op":"replace"},{"value":"DismissSwipeDirection","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DismissSwipeDirection"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/fragments"},{"value":"PWSwipeDismissUp","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissUp\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissUp\/fragments","value":[{"kind":"identifier","text":"PWSwipeDismissUp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissDown\/title","value":"PWSwipeDismissDown"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissDown\/fragments","op":"replace","value":[{"text":"PWSwipeDismissDown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissNone\/title","value":"PWSwipeDismissNone","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissNone\/fragments","value":[{"text":"PWSwipeDismissNone","kind":"identifier"}],"op":"replace"}]}]}