{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAppDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIResponder"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIApplicationDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring"]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwappdelegate"]},{"paths":["\/documentation\/pushwooshframework\/pwappdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate\/window"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate\/UIApplicationDelegate-Implementations"],"title":"Default Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"PWAppDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAppDelegate"}],"externalID":"c:objc(cs)PWAppDelegate","role":"symbol","roleHeading":"Class","title":"PWAppDelegate","modules":[{"name":"PushwooshFramework"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)UIResponder":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIResponder","title":"UIResponder"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWAppDelegate/UIApplicationDelegate-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate\/UIApplicationDelegate-Implementations","url":"\/documentation\/pushwooshframework\/pwappdelegate\/uiapplicationdelegate-implementations","title":"UIApplicationDelegate Implementations","type":"topic","role":"collectionGroup"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIApplicationDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIApplicationDelegate","title":"UIApplicationDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWAppDelegate/window":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate\/window","type":"topic","title":"window","url":"\/documentation\/pushwooshframework\/pwappdelegate\/window","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"window","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWAppDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate","title":"PWAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWAppDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PWAppDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwappdelegate","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PWAppDelegate"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWAppDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PWAppDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWAppDelegate\/window"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIResponder"]},{"type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIApplicationDelegate"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"PWAppDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIResponder","text":"UIResponder"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"window","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWAppDelegate~1window\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWAppDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWAppDelegate\/title","value":"PWAppDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWAppDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWAppDelegate\/fragments"}]}]}