{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager"]},{"paths":["\/documentation\/pushwooshframework\/pwinappmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/addJavascriptInterface(_:withName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/mergeUserId(_:to:doMerge:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/reloadInApps(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/resetBusinessCasesFrequencyCapping()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setEmails(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUser(_:emails:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:completion:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/shared()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/updateInstance()"],"title":"Type Methods"}],"kind":"symbol","metadata":{"title":"PWInAppManager","externalID":"c:objc(cs)PWInAppManager","role":"symbol","navigatorTitle":[{"text":"PWInAppManager","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInAppManager"}],"modules":[{"name":"PushwooshFramework"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInAppManager"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/updateInstance()":{"url":"\/documentation\/pushwooshframework\/pwinappmanager\/updateinstance()","kind":"symbol","title":"updateInstance()","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/updateInstance()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateInstance","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"updateInAppManagerInstance"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/resetBusinessCasesFrequencyCapping()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/resetBusinessCasesFrequencyCapping()","title":"resetBusinessCasesFrequencyCapping()","role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinappmanager\/resetbusinesscasesfrequencycapping()","abstract":[{"text":"Resets capping of the Pushwoosh out-of-the-box In-App solutions.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetBusinessCasesFrequencyCapping"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resetBusinessCasesFrequencyCapping","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/setUserId(_:)":{"abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"type":"text","text":" "},{"text":"This allows data and events to be matched across multiple user devices.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:)","url":"\/documentation\/pushwooshframework\/pwinappmanager\/setuserid(_:)","navigatorTitle":[{"kind":"identifier","text":"setUserId:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"kind":"symbol","role":"symbol","title":"setUserId(_:)","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/postEvent(_:withAttributes:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"postEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withAttributes"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"title":"postEvent(_:withAttributes:)","url":"\/documentation\/pushwooshframework\/pwinappmanager\/postevent(_:withattributes:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"postEvent:withAttributes:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:)","role":"symbol","abstract":[{"text":"See ","type":"text"},{"code":"postEvent:withAttributes:completion:","type":"codeVoice"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager":{"url":"\/documentation\/pushwooshframework\/pwinappmanager","title":"PWInAppManager","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInAppManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWInAppManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/addJavascriptInterface(_:withName:)":{"url":"\/documentation\/pushwooshframework\/pwinappmanager\/addjavascriptinterface(_:withname:)","role":"symbol","navigatorTitle":[{"text":"addJavascriptInterface:withName:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/addJavascriptInterface(_:withName:)","title":"addJavascriptInterface(_:withName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addJavascriptInterface","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWJavaScriptInterface","text":"PWJavaScriptInterface","kind":"typeIdentifier"},{"kind":"text","text":")!, "},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"type":"topic","abstract":[{"text":"Adds javascript interface for In-App Messages. Interface will be accessible from javascript as object with specified ","type":"text"},{"code":"name","type":"codeVoice"},{"text":" and functions defined in ","type":"text"},{"code":"interface","type":"codeVoice"},{"type":"text","text":" class."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/shared()":{"role":"symbol","title":"shared()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/shared()","kind":"symbol","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinappmanager\/shared()","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/mergeUserId(_:to:doMerge:completion:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/mergeUserId(_:to:doMerge:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mergeUserId"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"doMerge"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinappmanager\/mergeuserid(_:to:domerge:completion:)","type":"topic","title":"mergeUserId(_:to:doMerge:completion:)","abstract":[{"text":"Move all events from oldUserId to newUserId if doMerge is true. If doMerge is false all events for oldUserId are removed.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/setUser(_:emails:completion:)":{"title":"setUser(_:emails:completion:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setUser:emails:completion:"}],"url":"\/documentation\/pushwooshframework\/pwinappmanager\/setuser(_:emails:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"emails","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUser(_:emails:completion:)","abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"text":" ","type":"text"},{"text":"This allows data and events to be matched across multiple user devices.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/postEvent(_:withAttributes:completion:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinappmanager\/postevent(_:withattributes:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:completion:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"postEvent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withAttributes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"abstract":[{"type":"text","text":"Post events for In-App Messages. This can trigger In-App message display as specified in Pushwoosh Control Panel."}],"title":"postEvent(_:withAttributes:completion:)","navigatorTitle":[{"kind":"identifier","text":"postEvent:withAttributes:completion:"}]},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/setUserId(_:completion:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:completion:)","url":"\/documentation\/pushwooshframework\/pwinappmanager\/setuserid(_:completion:)","navigatorTitle":[{"text":"setUserId:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"kind":"symbol","role":"symbol","title":"setUserId(_:completion:)","abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"text":" ","type":"text"},{"text":"This allows data and events to be matched across multiple user devices.","type":"text"},{"type":"text","text":" "},{"text":"If setUser succeeds competion is called with nil argument. If setUser fails completion is called with error.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/setEmails(_:completion:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setEmails(_:completion:)","title":"setEmails(_:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setEmails","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"setEmails:completion:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinappmanager\/setemails(_:completion:)","abstract":[{"type":"text","text":"Register emails list associated to the current user."}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/reloadInApps(completion:)":{"url":"\/documentation\/pushwooshframework\/pwinappmanager\/reloadinapps(completion:)","role":"symbol","navigatorTitle":[{"text":"reloadInAppsWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/reloadInApps(completion:)","title":"reloadInApps(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadInApps","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!)","kind":"text"}],"type":"topic","abstract":[{"text":"Updates In-App messages storage on a device","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PWInAppManager","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PWInAppManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PWInAppManager","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/addJavascriptInterface(_:withName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/mergeUserId(_:to:doMerge:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/postEvent(_:withAttributes:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/reloadInApps(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/resetBusinessCasesFrequencyCapping()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setEmails(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUser(_:emails:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:completion:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/shared()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/updateInstance()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInAppManager"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"updateInAppManagerInstance","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1updateInstance()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1updateInstance()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updateInAppManagerInstance"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1resetBusinessCasesFrequencyCapping()\/title","value":"resetBusinessCasesFrequencyCapping","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetBusinessCasesFrequencyCapping"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1resetBusinessCasesFrequencyCapping()\/fragments"},{"value":"setUserId:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setUserId:"}]},{"value":"postEvent:withAttributes:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1postEvent(_:withAttributes:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"postEvent:withAttributes:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1postEvent(_:withAttributes:)\/fragments"},{"op":"replace","value":"PWInAppManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/title"},{"value":[{"text":"PWInAppManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/fragments"},{"op":"replace","value":"addJavascriptInterface:withName:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1addJavascriptInterface(_:withName:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addJavascriptInterface:withName:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1addJavascriptInterface(_:withName:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1shared()\/title","value":"sharedManager","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1shared()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sharedManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1mergeUserId(_:to:doMerge:completion:)\/title","op":"replace","value":"mergeUserId:to:doMerge:completion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1mergeUserId(_:to:doMerge:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUser(_:emails:completion:)\/title","value":"setUser:emails:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUser(_:emails:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUser:emails:completion:"}]},{"value":"postEvent:withAttributes:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1postEvent(_:withAttributes:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1postEvent(_:withAttributes:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postEvent:withAttributes:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:completion:)\/title","value":"setUserId:completion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setUserId:completion:","kind":"identifier"}]},{"value":"setEmails:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setEmails(_:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"setEmails:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setEmails(_:completion:)\/fragments","op":"replace"},{"value":"reloadInAppsWithCompletion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1reloadInApps(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1reloadInApps(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reloadInAppsWithCompletion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}