{"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshiOS\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappview"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/identifier"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"languages":["swift"]}]}],"metadata":{"title":"PWInlineInAppView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInlineInAppView","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"text":"PWInlineInAppView","kind":"identifier"}],"externalID":"c:objc(cs)PWInlineInAppView","roleHeading":"Class","symbolKind":"class"},"references":{"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView/identifier":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"title":"identifier","url":"\/documentation\/pushwooshframework\/pwinlineinappview\/identifier","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView","title":"UIView"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView/delegate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)PWInlineInAppViewDelegate","kind":"typeIdentifier","text":"PWInlineInAppViewDelegate"},{"kind":"text","text":")!"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview\/delegate","title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/delegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview","title":"PWInlineInAppView","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppView"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"PWInlineInAppView","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PWInlineInAppView","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWInlineInAppView"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView\/identifier"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWInlineInAppView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1identifier\/title"},{"op":"replace","value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1identifier\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/title","value":"PWInlineInAppView"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/fragments","value":[{"text":"PWInlineInAppView","kind":"identifier"}]}]}]}