{"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"sections":[],"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessageProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"PWInboxMessageProtocol"}],"roleHeading":"Protocol","externalID":"c:objc(pl)PWInboxMessageProtocol","title":"PWInboxMessageProtocol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol"]}],"abstract":[{"type":"codeVoice","code":"PWInboxMessageProtocol"},{"type":"text","text":" The protocol describing the Inbox message."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/actionParams","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/attachmentUrl","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/code","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/imageUrl","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isActionPerformed","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isRead","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/message","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/sendDate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/title","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/type"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/type":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PWInboxMessageType","kind":"typeIdentifier","text":"PWInboxMessageType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/type","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/type","title":"type","required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/isActionPerformed":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isActionPerformed"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/isactionperformed","required":true,"role":"symbol","navigatorTitle":[{"text":"isActionPerformed","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isActionPerformed","title":"isActionPerformed","abstract":[{"text":"Action of the Inbox Message is performed (if true, an action was performed in the Inbox see + (void)performActionForMessageWithCode:(NSString *)code or an action was performed on the push tap )","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/sendDate":{"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendDate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"sendDate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/sendDate","title":"sendDate","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/senddate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/title":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/title","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/title","required":true,"navigatorTitle":[{"kind":"identifier","text":"title"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","role":"symbol","title":"title","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/attachmentUrl":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/attachmentUrl","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"attachmentUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"attachmentUrl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/attachmenturl","title":"attachmentUrl","required":true,"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWInboxMessageProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"PWInboxMessageProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol","title":"PWInboxMessageProtocol","abstract":[{"type":"codeVoice","code":"PWInboxMessageProtocol"},{"type":"text","text":" The protocol describing the Inbox message."}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/isRead":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isRead","title":"isRead","role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/isread","abstract":[{"type":"text","text":"Inbox Message which is read, see + (void)readMessagesWithCodes:(NSArray<NSString *> *)codes"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRead","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRead"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/actionParams":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/actionParams","title":"actionParams","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/actionparams","kind":"symbol","abstract":[],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionParams","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"actionParams","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/message":{"required":true,"type":"topic","title":"message","role":"symbol","navigatorTitle":[{"text":"message","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/message","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/message","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/code":{"abstract":[],"title":"code","navigatorTitle":[{"text":"code","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/code","type":"topic","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/code","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/imageUrl":{"navigatorTitle":[{"kind":"identifier","text":"imageUrl"}],"url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/imageurl","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/imageUrl","role":"symbol","type":"topic","abstract":[],"title":"imageUrl","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PWInboxMessageProtocol"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"PWInboxMessageProtocol","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWInboxMessageProtocol"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/actionParams","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/attachmentUrl","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/code","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/imageUrl","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isActionPerformed","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isRead","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/message","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/sendDate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/title","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/type"]}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessageProtocol"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"value":"isActionPerformed","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isActionPerformed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isActionPerformed"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isActionPerformed\/fragments"},{"value":"sendDate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1sendDate\/title"},{"value":[{"kind":"identifier","text":"sendDate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1sendDate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1title\/title","op":"replace","value":"title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1title\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"value":"attachmentUrl","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1attachmentUrl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1attachmentUrl\/fragments","value":[{"kind":"identifier","text":"attachmentUrl"}]},{"op":"replace","value":"PWInboxMessageProtocol","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/fragments","value":[{"text":"PWInboxMessageProtocol","kind":"identifier"}]},{"value":"isRead","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isRead\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isRead\/fragments","value":[{"text":"isRead","kind":"identifier"}],"op":"replace"},{"value":"actionParams","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1actionParams\/title","op":"replace"},{"value":[{"text":"actionParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1actionParams\/fragments","op":"replace"},{"value":"message","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1message\/title"},{"value":[{"text":"message","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1message\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1code\/title","op":"replace","value":"code"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1code\/fragments","value":[{"text":"code","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1imageUrl\/title","value":"imageUrl","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1imageUrl\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageUrl"}]}]}]}