{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptcallback"]},{"paths":["\/documentation\/pushwooshframework\/pwjavascriptcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"type":"conformsTo"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWJavaScriptCallback","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback"},"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWJavaScriptCallback","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWJavaScriptCallback","kind":"identifier"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","title":"PWJavaScriptCallback","navigatorTitle":[{"text":"PWJavaScriptCallback","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParam:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParams:)"]}],"abstract":[{"code":"PWJavaScriptCallback","type":"codeVoice"},{"text":" is a representation of Javascript function","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback/execute(withParams:)":{"abstract":[{"type":"text","text":"Invokes callback with multiple arguments"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParams:)","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute(withparams:)","navigatorTitle":[{"kind":"identifier","text":"executeWithParams:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"execute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withParams","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","role":"symbol","title":"execute(withParams:)","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback","navigatorTitle":[{"text":"PWJavaScriptCallback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWJavaScriptCallback"}],"kind":"symbol","role":"symbol","title":"PWJavaScriptCallback","abstract":[{"code":"PWJavaScriptCallback","type":"codeVoice"},{"text":" is a representation of Javascript function","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback/execute(withParam:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute(withparam:)","abstract":[{"type":"text","text":"Invokes callback with one argument"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"execute"},{"text":"(","kind":"text"},{"text":"withParam","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!) -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"type":"topic","title":"execute(withParam:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParam:)","navigatorTitle":[{"text":"executeWithParam:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptCallback/execute()":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute()","navigatorTitle":[{"text":"execute","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwjavascriptcallback\/execute()","abstract":[{"type":"text","text":"Invokes callback with no arguments"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"execute","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"role":"symbol","title":"execute()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"PWJavaScriptCallback","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"PWJavaScriptCallback","kind":"identifier"}],"op":"replace"},{"value":[{"text":"PWJavaScriptCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParam:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptCallback\/execute(withParams:)"],"title":"Instance Methods"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWJavaScriptCallback","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"executeWithParams:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParams:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"executeWithParams:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParams:)\/fragments"},{"value":"PWJavaScriptCallback","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWJavaScriptCallback"}]},{"value":"executeWithParam:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParam:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"executeWithParam:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute(withParam:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute()\/title","value":"execute","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"execute"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptCallback~1execute()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}