{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwlog"]},{"paths":["\/documentation\/pushwooshframework\/pwlog"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWLog","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/removeLogsHandler()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/setLogsHandler(_:)"]}],"sections":[],"metadata":{"externalID":"c:objc(cs)PWLog","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWLog","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"PushwooshFramework"}],"role":"symbol","title":"PWLog","navigatorTitle":[{"kind":"identifier","text":"PWLog"}],"roleHeading":"Class"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLog/setLogsHandler(_:)":{"abstract":[],"kind":"symbol","type":"topic","title":"setLogsHandler(_:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLogsHandler"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"},{"text":"?, ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"setLogsHandler:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwlog\/setlogshandler(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/setLogsHandler(_:)"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLog":{"abstract":[],"kind":"symbol","type":"topic","title":"PWLog","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWLog","kind":"identifier"}],"navigatorTitle":[{"text":"PWLog","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwlog","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLog/removeLogsHandler()":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/removeLogsHandler()","title":"removeLogsHandler()","abstract":[],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwlog\/removelogshandler()","navigatorTitle":[{"text":"removeLogsHandler","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeLogsHandler","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"PWLog","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"PWLog","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"PWLog","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/removeLogsHandler()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/setLogsHandler(_:)"]}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWLog","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"setLogsHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1setLogsHandler(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1setLogsHandler(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setLogsHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog\/title","value":"PWLog","op":"replace"},{"op":"replace","value":[{"text":"PWLog","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog\/fragments"},{"value":"removeLogsHandler","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1removeLogsHandler()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeLogsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1removeLogsHandler()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}