{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"roleHeading":"Structure","title":"PWLogLevel","role":"symbol","externalID":"c:PWLog.h@T@PWLogLevel","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/init(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/none"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/_SwiftNewtypeWrapper-Implementations"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PWLogLevel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwloglevel"]},{"paths":["\/documentation\/pushwooshframework\/pwloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel":{"url":"\/documentation\/pushwooshframework\/pwloglevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","abstract":[],"kind":"symbol","title":"PWLogLevel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/none":{"url":"\/documentation\/pushwooshframework\/pwloglevel\/none","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/none","abstract":[],"title":"none","kind":"symbol","navigatorTitle":[{"text":"PWLogLevelNone","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"},"doc://com.pushwoosh.PushwooshiOS/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY"},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/init(rawValue:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwloglevel\/init(rawvalue:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/_SwiftNewtypeWrapper-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/pushwooshframework\/pwloglevel\/_swiftnewtypewrapper-implementations","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/_SwiftNewtypeWrapper-Implementations","title":"_SwiftNewtypeWrapper Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/init(_:)":{"url":"\/documentation\/pushwooshframework\/pwloglevel\/init(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/init(_:)","abstract":[],"kind":"symbol","title":"init(_:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/pushwooshframework\/pwloglevel\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/Equatable-Implementations"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"value":"PWLogLevel","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"value":[{"text":"PWLogLevel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"PWLogLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/none"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"PWLogLevel"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PWLogLevel","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/title"},{"value":[{"text":"PWLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1none\/title","op":"replace","value":"PWLogLevelNone"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1none\/fragments","value":[{"text":"PWLogLevelNone","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}