{"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshiOS\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWLoadingView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwloadingview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwloadingview"]}],"metadata":{"navigatorTitle":[{"text":"PWLoadingView","kind":"identifier"}],"role":"symbol","symbolKind":"class","title":"PWLoadingView","externalID":"c:objc(cs)PWLoadingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWLoadingView","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"PushwooshFramework"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/activityIndicatorView","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/cancelLoadingButton"],"title":"Instance Properties"}],"references":{"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIUserActivityRestoring"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView":{"abstract":[],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwloadingview","title":"PWLoadingView","type":"topic","role":"symbol","navigatorTitle":[{"text":"PWLoadingView","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWLoadingView"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)CALayerDelegate"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UITraitEnvironment"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UILargeContentViewerItem"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView/activityIndicatorView":{"url":"\/documentation\/pushwooshframework\/pwloadingview\/activityindicatorview","role":"symbol","navigatorTitle":[{"text":"activityIndicatorView","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/activityIndicatorView","title":"activityIndicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"activityIndicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"text":"!","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView","title":"UIView"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","title":"Swift.Sendable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView/cancelLoadingButton":{"abstract":[],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwloadingview\/cancelloadingbutton","title":"cancelLoadingButton","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelLoadingButton"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/cancelLoadingButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelLoadingButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":"!","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"PWLoadingView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"PWLoadingView"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"PWLoadingView","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/activityIndicatorView","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/cancelLoadingButton"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWLoadingView"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/title","value":"PWLoadingView","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/fragments","value":[{"text":"PWLoadingView","kind":"identifier"}],"op":"replace"},{"value":"activityIndicatorView","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1activityIndicatorView\/title"},{"value":[{"kind":"identifier","text":"activityIndicatorView"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1activityIndicatorView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1cancelLoadingButton\/title","value":"cancelLoadingButton","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1cancelLoadingButton\/fragments","value":[{"text":"cancelLoadingButton","kind":"identifier"}],"op":"replace"}]}]}