{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/closeModalWindow(after:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/configureModalWindow(with:present:dismiss:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/presentModalWindow(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setCornerType(_:withRadius:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setDismissSwipeDirections(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setPresent(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/shared()"]}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"class","role":"symbol","externalID":"c:objc(cs)PWModalWindowConfiguration","title":"PWModalWindowConfiguration","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWModalWindowConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/setCornerType(_:withRadius:)":{"role":"symbol","title":"setCornerType(_:withRadius:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setCornerType(_:withRadius:)","kind":"symbol","navigatorTitle":[{"text":"setCornerType:withRadius:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setcornertype(_:withradius:)","abstract":[{"type":"text","text":"Sets the corner type and radius for rounding specific corners of the view."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCornerType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CornerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType"},{"text":", ","kind":"text"},{"text":"withRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/closeModalWindow(after:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeModalWindow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/closemodalwindow(after:)","abstract":[{"type":"text","text":"Schedules the automatic closing of the modal window after a specified time interval."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/closeModalWindow(after:)","title":"closeModalWindow(after:)","navigatorTitle":[{"text":"closeModalWindowAfter:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/presentModalWindow(_:)":{"role":"symbol","title":"presentModalWindow(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/presentModalWindow(_:)","kind":"symbol","navigatorTitle":[{"text":"presentModalWindow:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/presentmodalwindow(_:)","abstract":[{"text":"Presents the modal window with the specified rich media content.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentModalWindow"},{"text":"(","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/configureModalWindow(with:present:dismiss:)":{"role":"symbol","title":"configureModalWindow(with:present:dismiss:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/configureModalWindow(with:present:dismiss:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureModalWindowWith:presentAnimation:dismissAnimation:"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/configuremodalwindow(with:present:dismiss:)","abstract":[{"type":"text","text":"Configures the modal window to be displayed at a specified position on the screen and defines the animation styles for presenting and dismissing the window."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureModalWindow"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ModalWindowPosition","text":"ModalWindowPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"present"},{"text":": ","kind":"text"},{"text":"PresentModalWindowAnimation","preciseIdentifier":"c:@E@PresentModalWindowAnimation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismiss","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@DismissModalWindowAnimation","text":"DismissModalWindowAnimation","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/setDismissSwipeDirections(_:)":{"role":"symbol","title":"setDismissSwipeDirections(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setDismissSwipeDirections(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDismissSwipeDirections:"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setdismissswipedirections(_:)","abstract":[{"type":"text","text":"Configures swipe gestures for interacting with the modal window. These gestures allow the user to dismiss the window by swiping in specified directions."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDismissSwipeDirections","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"])"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/shared()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/shared()","abstract":[{"type":"text","text":"Provides access to the shared instance of the modal window manager."}],"title":"shared()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/shared()","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/setPresent(_:)":{"abstract":[{"type":"text","text":"Sets the type of haptic feedback that will be triggered when the modal window is presented."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPresent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@HapticFeedbackType","text":"HapticFeedbackType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setPresentHapticFeedbackType:"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setpresent(_:)","type":"topic","title":"setPresent(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setPresent(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"PWModalWindowConfiguration","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/closeModalWindow(after:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/configureModalWindow(with:present:dismiss:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/presentModalWindow(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setCornerType(_:withRadius:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setDismissSwipeDirections(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setPresent(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/shared()"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWModalWindowConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setCornerType(_:withRadius:)\/title","value":"setCornerType:withRadius:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setCornerType:withRadius:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setCornerType(_:withRadius:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1closeModalWindow(after:)\/title","value":"closeModalWindowAfter:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"closeModalWindowAfter:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1closeModalWindow(after:)\/fragments"},{"value":"presentModalWindow:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1presentModalWindow(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1presentModalWindow(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentModalWindow:","kind":"identifier"}]},{"op":"replace","value":"configureModalWindowWith:presentAnimation:dismissAnimation:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1configureModalWindow(with:present:dismiss:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1configureModalWindow(with:present:dismiss:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureModalWindowWith:presentAnimation:dismissAnimation:"}]},{"op":"replace","value":"setDismissSwipeDirections:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setDismissSwipeDirections(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setDismissSwipeDirections(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setDismissSwipeDirections:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1shared()\/title","value":"shared"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"shared"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1shared()\/fragments"},{"value":"setPresentHapticFeedbackType:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setPresent(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setPresent(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPresentHapticFeedbackType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title","value":"PWModalWindowConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}