{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/inApp","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/push"]},{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/SY","doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediasource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediasource"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Enumeration","title":"PWRichMediaSource","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"externalID":"c:@E@PWRichMediaSource","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSource"}],"modules":[{"name":"PushwooshFramework"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/inApp":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inApp","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource\/inapp","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/inApp","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSourceInApp"}],"role":"symbol","type":"topic","title":"PWRichMediaSource.inApp","kind":"symbol","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/pushwooshframework\/pwrichmediasource\/equatable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/pushwooshframework\/pwrichmediasource\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/push":{"abstract":[],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediasource\/push","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/push","navigatorTitle":[{"text":"PWRichMediaSourcePush","kind":"identifier"}],"title":"PWRichMediaSource.push"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSource"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource","title":"PWRichMediaSource","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SY","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediasource\/init(rawvalue:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PWRichMediaSource"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PWRichMediaSource","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaSource"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/inApp","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/push"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1inApp\/title","value":"PWRichMediaSourceInApp"},{"value":[{"text":"PWRichMediaSourceInApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1inApp\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1push\/title","value":"PWRichMediaSourcePush","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1push\/fragments","value":[{"kind":"identifier","text":"PWRichMediaSourcePush"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/title","value":"PWRichMediaSource"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/fragments","op":"replace","value":[{"text":"PWRichMediaSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}