{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleCrossFadeAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideBottomAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideLeftAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideRightAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideTopAnimation"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate"]}],"metadata":{"symbolKind":"protocol","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"roleHeading":"Protocol","title":"PWRichMediaStyleAnimationDelegate","role":"symbol","externalID":"c:objc(pl)PWRichMediaStyleAnimationDelegate","navigatorTitle":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate"},"sections":[],"abstract":[{"type":"text","text":"Interface for Rich Media Custom Animation."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMediaStyleAnimationDelegate"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runDismissingAnimation(withContentView:parentView:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runPresentingAnimation(withContentView:parentView:completion:)"],"title":"Instance Methods"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleSlideRightAnimation":{"abstract":[],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastylesliderightanimation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMediaStyleSlideRightAnimation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideRightAnimation","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyleSlideRightAnimation"}],"title":"PWRichMediaStyleSlideRightAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate/runPresentingAnimation(withContentView:parentView:completion:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runPresentingAnimation(withContentView:parentView:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"runPresentingAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withContentView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"!, "},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"title":"runPresentingAnimation(withContentView:parentView:completion:)","navigatorTitle":[{"kind":"identifier","text":"runPresentingAnimationWithContentView:parentView:completion:"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate\/runpresentinganimation(withcontentview:parentview:completion:)","role":"symbol","required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate":{"abstract":[{"text":"Interface for Rich Media Custom Animation.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate","navigatorTitle":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"title":"PWRichMediaStyleAnimationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleSlideTopAnimation":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideTopAnimation","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleSlideTopAnimation","kind":"identifier"}],"title":"PWRichMediaStyleSlideTopAnimation","navigatorTitle":[{"text":"PWRichMediaStyleSlideTopAnimation","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyleslidetopanimation","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleCrossFadeAnimation":{"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyleCrossFadeAnimation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleCrossFadeAnimation","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/pwrichmediastylecrossfadeanimation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMediaStyleCrossFadeAnimation"}],"title":"PWRichMediaStyleCrossFadeAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleSlideLeftAnimation":{"navigatorTitle":[{"text":"PWRichMediaStyleSlideLeftAnimation","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideLeftAnimation","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwrichmediastyleslideleftanimation","abstract":[{"type":"text","text":"Built-in Rich Media presenting animations."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMediaStyleSlideLeftAnimation"}],"title":"PWRichMediaStyleSlideLeftAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleSlideBottomAnimation":{"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyleSlideBottomAnimation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideBottomAnimation","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework\/pwrichmediastyleslidebottomanimation","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWRichMediaStyleSlideBottomAnimation","kind":"identifier"}],"title":"PWRichMediaStyleSlideBottomAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate/runDismissingAnimation(withContentView:parentView:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"runDismissingAnimationWithContentView:parentView:completion:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runDismissingAnimation(withContentView:parentView:completion:)","role":"symbol","kind":"symbol","required":true,"abstract":[{"type":"text","text":"This method can be used to animate Rich Media dismissing view."}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate\/rundismissinganimation(withcontentview:parentview:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"runDismissingAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withContentView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"title":"runDismissingAnimation(withContentView:parentView:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PWRichMediaStyleAnimationDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"PWRichMediaStyleAnimationDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runDismissingAnimation(withContentView:parentView:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate\/runPresentingAnimation(withContentView:parentView:completion:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleCrossFadeAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideBottomAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideLeftAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideRightAnimation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleSlideTopAnimation"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"value":"PWRichMediaStyleSlideRightAnimation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideRightAnimation\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWRichMediaStyleSlideRightAnimation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideRightAnimation\/fragments"},{"op":"replace","value":"runPresentingAnimationWithContentView:parentView:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runPresentingAnimation(withContentView:parentView:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runPresentingAnimation(withContentView:parentView:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"runPresentingAnimationWithContentView:parentView:completion:"}]},{"value":"PWRichMediaStyleAnimationDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaStyleAnimationDelegate"}]},{"value":"PWRichMediaStyleSlideTopAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideTopAnimation\/title"},{"value":[{"text":"PWRichMediaStyleSlideTopAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideTopAnimation\/fragments","op":"replace"},{"value":"PWRichMediaStyleCrossFadeAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleCrossFadeAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleCrossFadeAnimation\/fragments","value":[{"text":"PWRichMediaStyleCrossFadeAnimation","kind":"identifier"}]},{"value":"PWRichMediaStyleSlideLeftAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideLeftAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideLeftAnimation\/fragments","value":[{"text":"PWRichMediaStyleSlideLeftAnimation","kind":"identifier"}]},{"value":"PWRichMediaStyleSlideBottomAnimation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideBottomAnimation\/title","op":"replace"},{"op":"replace","value":[{"text":"PWRichMediaStyleSlideBottomAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleSlideBottomAnimation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runDismissingAnimation(withContentView:parentView:completion:)\/title","value":"runDismissingAnimationWithContentView:parentView:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"runDismissingAnimationWithContentView:parentView:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate~1runDismissingAnimation(withContentView:parentView:completion:)\/fragments"}]}]}