{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediamanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediamanager"]}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/richMediaStyle"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/present(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/shared()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"title":"PWRichMediaManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Class","externalID":"c:objc(cs)PWRichMediaManager"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMediaManager"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager/shared()":{"url":"\/documentation\/pushwooshframework\/pwrichmediamanager\/shared()","type":"topic","title":"shared()","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"abstract":[{"text":"A singleton object that represents the rich media manager.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/shared()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager/delegate":{"title":"delegate","kind":"symbol","abstract":[{"text":"Delegate for Rich Media presentation managing.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/delegate","url":"\/documentation\/pushwooshframework\/pwrichmediamanager\/delegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"PWRichMediaPresentingDelegate","preciseIdentifier":"c:objc(pl)PWRichMediaPresentingDelegate"},{"text":")!","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager/present(_:)":{"url":"\/documentation\/pushwooshframework\/pwrichmediamanager\/present(_:)","type":"topic","title":"present(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier","text":"PWRichMedia"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"presentRichMedia:","kind":"identifier"}],"abstract":[{"text":"Presents the rich media object.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/present(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager/richMediaStyle":{"url":"\/documentation\/pushwooshframework\/pwrichmediamanager\/richmediastyle","type":"topic","title":"richMediaStyle","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaStyle"},{"text":": ","kind":"text"},{"text":"PWRichMediaStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaStyle"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"richMediaStyle","kind":"identifier"}],"abstract":[{"text":"Style for Rich Media presenting.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/richMediaStyle"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"PWRichMediaManager","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWRichMediaManager"}]},{"value":[{"text":"PWRichMediaManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/richMediaStyle"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/present(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager\/shared()"]}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWRichMediaManager"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1shared()\/title","value":"sharedManager","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"sharedManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1shared()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1delegate\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1present(_:)\/title","op":"replace","value":"presentRichMedia:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1present(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentRichMedia:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1richMediaStyle\/title","value":"richMediaStyle"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager~1richMediaStyle\/fragments","value":[{"text":"richMediaStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title","value":"PWRichMediaManager","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments","value":[{"kind":"identifier","text":"PWRichMediaManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}