{"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Type Property","externalID":"c:@E@CornerType@PWCornerTypeBottomLeft","navigatorTitle":[{"text":"PWCornerTypeBottomLeft","kind":"identifier"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"PWCornerTypeBottomLeft","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType","text":"CornerType"}],"title":"PWCornerTypeBottomLeft"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomLeft"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWCornerTypeBottomLeft"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","text":"CornerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomleft"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeBottomLeft":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeBottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType","text":"CornerType"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeBottomLeft"}],"role":"symbol","abstract":[],"title":"PWCornerTypeBottomLeft","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeBottomLeft","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypebottomleft"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PWCornerTypeBottomLeft"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWCornerTypeBottomLeft"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PWCornerTypeBottomLeft","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType"},{"op":"replace","value":[{"text":"CornerType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomLeft\/title","value":"PWCornerTypeBottomLeft"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeBottomLeft\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWCornerTypeBottomLeft"}]}]}]}