{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/inlineInAppDidLoad(in:)","interfaceLanguage":"swift"},"metadata":{"title":"inlineInAppDidLoad(in:)","modules":[{"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inlineInAppDidLoad"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView","text":"PWInlineInAppView"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"inlineInAppDidLoadInView:","kind":"identifier"}],"externalID":"c:objc(pl)PWInlineInAppViewDelegate(im)inlineInAppDidLoadInView:","roleHeading":"Instance Method","required":true},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inlineInAppDidLoad"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"inAppView","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView","text":"PWInlineInAppView"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/inlineinappdidload(in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/inlineinappdidload(in:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview","title":"PWInlineInAppView","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppView"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate","title":"PWInlineInAppViewDelegate","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/inlineInAppDidLoad(in:)":{"kind":"symbol","type":"topic","title":"inlineInAppDidLoad(in:)","required":true,"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/inlineinappdidload(in:)","abstract":[],"navigatorTitle":[{"text":"inlineInAppDidLoadInView:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/inlineInAppDidLoad(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"inlineInAppDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"text":"!)","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"inlineInAppDidLoadInView:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"inlineInAppDidLoadInView:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"inlineInAppDidLoadInView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView"},{"kind":"text","text":" *) "},{"text":"inAppView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"PWInlineInAppView","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PWInlineInAppView"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/fragments"},{"value":"PWInlineInAppViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/fragments","value":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"op":"replace"},{"op":"replace","value":"inlineInAppDidLoadInView:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1inlineInAppDidLoad(in:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1inlineInAppDidLoad(in:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"inlineInAppDidLoadInView:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}