{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@IBOutlet","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activityIndicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwloadingview\/activityindicatorview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwloadingview\/activityindicatorview"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/activityIndicatorView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"activityIndicatorView"}],"symbolKind":"property","externalID":"c:objc(cs)PWLoadingView(py)activityIndicatorView","role":"symbol","title":"activityIndicatorView","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activityIndicatorView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"text":"!","kind":"text"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView":{"abstract":[],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwloadingview","title":"PWLoadingView","type":"topic","role":"symbol","navigatorTitle":[{"text":"PWLoadingView","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWLoadingView"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLoadingView/activityIndicatorView":{"url":"\/documentation\/pushwooshframework\/pwloadingview\/activityindicatorview","role":"symbol","navigatorTitle":[{"text":"activityIndicatorView","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLoadingView\/activityIndicatorView","title":"activityIndicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"activityIndicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"text":"!","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"activityIndicatorView","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"activityIndicatorView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView"},{"text":" * ","kind":"text"},{"text":"activityIndicatorView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PWLoadingView","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView\/fragments","op":"replace","value":[{"text":"PWLoadingView","kind":"identifier"}]},{"value":"activityIndicatorView","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1activityIndicatorView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLoadingView~1activityIndicatorView\/fragments","value":[{"text":"activityIndicatorView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}