{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/shared()"]},{"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/shared()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}]}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)PWInAppManager(cm)sharedManager","title":"shared()","roleHeading":"Type Method","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/shared()"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/shared()":{"role":"symbol","title":"shared()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/shared()","kind":"symbol","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinappmanager\/shared()","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager":{"url":"\/documentation\/pushwooshframework\/pwinappmanager","title":"PWInAppManager","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInAppManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWInAppManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sharedManager","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sharedManager"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sharedManager","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1shared()\/title","value":"sharedManager","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1shared()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/title","value":"PWInAppManager"},{"value":[{"text":"PWInAppManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/fragments"}]}]}