{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType\/URL","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URL","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Case","externalID":"c:@E@PWInboxMessageType@PWInboxMessageTypeURL","title":"PWInboxMessageType.URL","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessageTypeURL"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URL","kind":"identifier"}],"symbolKind":"case","role":"symbol"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinboxmessagetype\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinboxmessagetype\/url"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInboxMessageType"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType","kind":"symbol","title":"PWInboxMessageType","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessageType"}],"url":"\/documentation\/pushwooshframework\/pwinboxmessagetype","abstract":[{"type":"text","text":"The Inbox message type. Plain = without any action, Richmedia = contains a Rich media page, URL = contains remote URL, Deeplink = contains Deeplink"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageType/URL":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType\/URL","type":"topic","url":"\/documentation\/pushwooshframework\/pwinboxmessagetype\/url","title":"PWInboxMessageType.URL","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URL"}],"navigatorTitle":[{"kind":"identifier","text":"PWInboxMessageTypeURL"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PWInboxMessageTypeURL"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWInboxMessageTypeURL"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PWInboxMessageTypeURL","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType\/title","op":"replace","value":"PWInboxMessageType"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType\/fragments","value":[{"text":"PWInboxMessageType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType~1URL\/title","value":"PWInboxMessageTypeURL"},{"value":[{"text":"PWInboxMessageTypeURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType~1URL\/fragments","op":"replace"}]}]}