{"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"closeModalWindow","kind":"identifier"},{"kind":"text","text":"("},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","symbolKind":"method","title":"closeModalWindow(after:)","externalID":"c:objc(cs)PWModalWindowConfiguration(im)closeModalWindowAfter:","navigatorTitle":[{"kind":"identifier","text":"closeModalWindowAfter:"}]},"abstract":[{"type":"text","text":"Schedules the automatic closing of the modal window after a specified time interval."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeModalWindow"},{"text":"(","kind":"text"},{"text":"after","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interval","kind":"internalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time interval, in seconds, after which the modal window will be automatically closed."}]}],"name":"interval"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/closeModalWindow(after:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/closemodalwindow(after:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/closemodalwindow(after:)"]}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/closeModalWindow(after:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeModalWindow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/closemodalwindow(after:)","abstract":[{"type":"text","text":"Schedules the automatic closing of the modal window after a specified time interval."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/closeModalWindow(after:)","title":"closeModalWindow(after:)","navigatorTitle":[{"text":"closeModalWindowAfter:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"closeModalWindowAfter:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeModalWindowAfter:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"closeModalWindowAfter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"interval"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"closeModalWindowAfter:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1closeModalWindow(after:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1closeModalWindow(after:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"closeModalWindowAfter:"}]},{"value":"PWModalWindowConfiguration","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}]}]}]}