{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setcornertype(_:withradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setcornertype(_:withradius:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCornerType"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"text":"CornerType","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","preciseIdentifier":"c:@E@CornerType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withRadius"},{"text":" ","kind":"text"},{"text":"radius","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of corners to be rounded (e.g., top-left, bottom-right, or a combination)."}]}],"name":"type"},{"name":"radius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius of the corner rounding."}]}]}],"kind":"parameters"}],"abstract":[{"text":"Sets the corner type and radius for rounding specific corners of the view.","type":"text"}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"setCornerType:withRadius:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCornerType","kind":"identifier"},{"kind":"text","text":"("},{"text":"CornerType","preciseIdentifier":"c:@E@CornerType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:objc(cs)PWModalWindowConfiguration(im)setCornerType:withRadius:","title":"setCornerType(_:withRadius:)","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setCornerType(_:withRadius:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/setCornerType(_:withRadius:)":{"role":"symbol","title":"setCornerType(_:withRadius:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setCornerType(_:withRadius:)","kind":"symbol","navigatorTitle":[{"text":"setCornerType:withRadius:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setcornertype(_:withradius:)","abstract":[{"type":"text","text":"Sets the corner type and radius for rounding specific corners of the view."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCornerType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CornerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@CornerType"},{"text":", ","kind":"text"},{"text":"withRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"setCornerType:withRadius:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCornerType:withRadius:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setCornerType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CornerType","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","preciseIdentifier":"c:@E@CornerType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withRadius:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"radius","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments","value":[{"text":"CornerType","kind":"identifier"}]},{"value":"PWModalWindowConfiguration","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title","op":"replace"},{"op":"replace","value":[{"text":"PWModalWindowConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments"},{"op":"replace","value":"setCornerType:withRadius:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setCornerType(_:withRadius:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setCornerType(_:withRadius:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setCornerType:withRadius:","kind":"identifier"}],"op":"replace"}]}]}