{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPresent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HapticFeedbackType","kind":"typeIdentifier","preciseIdentifier":"c:@E@HapticFeedbackType"},{"text":")","kind":"text"}],"symbolKind":"method","title":"setPresent(_:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"setPresentHapticFeedbackType:","kind":"identifier"}],"externalID":"c:objc(cs)PWModalWindowConfiguration(im)setPresentHapticFeedbackType:","modules":[{"name":"PushwooshFramework"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"abstract":[{"text":"Sets the type of haptic feedback that will be triggered when the modal window is presented.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setPresent(_:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPresent"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"text":"HapticFeedbackType","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","preciseIdentifier":"c:@E@HapticFeedbackType"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of haptic feedback to be used (e.g., light, medium, heavy).","type":"text"}]}],"name":"type"}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setpresent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setpresent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/setPresent(_:)":{"abstract":[{"type":"text","text":"Sets the type of haptic feedback that will be triggered when the modal window is presented."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPresent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@HapticFeedbackType","text":"HapticFeedbackType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setPresentHapticFeedbackType:"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/setpresent(_:)","type":"topic","title":"setPresent(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/setPresent(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/HapticFeedbackType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","url":"\/documentation\/pushwooshframework\/hapticfeedbacktype","abstract":[{"type":"text","text":"Enum defining the types of haptic feedback that can be triggered when interacting with the modal window."}],"kind":"symbol","title":"HapticFeedbackType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticFeedbackType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HapticFeedbackType"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"setPresentHapticFeedbackType:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPresentHapticFeedbackType:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPresentHapticFeedbackType:"},{"kind":"text","text":"("},{"text":"HapticFeedbackType","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/HapticFeedbackType","preciseIdentifier":"c:@E@HapticFeedbackType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWModalWindowConfiguration","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments","value":[{"text":"PWModalWindowConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setPresent(_:)\/title","op":"replace","value":"setPresentHapticFeedbackType:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPresentHapticFeedbackType:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1setPresent(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/title","value":"HapticFeedbackType","op":"replace"},{"value":[{"kind":"identifier","text":"HapticFeedbackType"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1HapticFeedbackType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}