{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:objc(cs)PWModalWindowConfiguration(cm)shared","title":"shared()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/shared()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/shared()"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A singleton instance of the modal window manager.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/shared()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Provides access to the shared instance of the modal window manager.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration/shared()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration\/shared()","abstract":[{"type":"text","text":"Provides access to the shared instance of the modal window manager."}],"title":"shared()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration\/shared()","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWModalWindowConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowConfiguration"}],"url":"\/documentation\/pushwooshframework\/pwmodalwindowconfiguration","abstract":[],"kind":"symbol","title":"PWModalWindowConfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWModalWindowConfiguration","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowConfiguration"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"shared","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"shared","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"shared","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1shared()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration~1shared()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/title","value":"PWModalWindowConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWModalWindowConfiguration\/fragments","value":[{"kind":"identifier","text":"PWModalWindowConfiguration"}]}]}]}