{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"PushwooshFramework"}],"required":true,"title":"actionParams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"actionParams"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionParams","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"externalID":"c:objc(pl)PWInboxMessageProtocol(py)actionParams"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/actionParams"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionParams"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/actionparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/actionparams"]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/actionParams":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/actionParams","title":"actionParams","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/actionparams","kind":"symbol","abstract":[],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionParams","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"actionParams","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWInboxMessageProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"PWInboxMessageProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol","title":"PWInboxMessageProtocol","abstract":[{"type":"codeVoice","code":"PWInboxMessageProtocol"},{"type":"text","text":" The protocol describing the Inbox message."}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"actionParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"actionParams","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"actionParams"},{"text":";","kind":"text"}]}]}},{"value":"actionParams","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1actionParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"actionParams"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1actionParams\/fragments","op":"replace"},{"value":"PWInboxMessageProtocol","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/fragments","value":[{"kind":"identifier","text":"PWInboxMessageProtocol"}],"op":"replace"}]}]}