{"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isRead","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRead","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"isRead","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRead"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"isRead","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(pl)PWInboxMessageProtocol(py)isRead"},"abstract":[{"text":"Inbox Message which is read, see + (void)readMessagesWithCodes:(NSArray<NSString *> *)codes","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/isread"]},{"paths":["\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/isread"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol/isRead":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol\/isRead","title":"isRead","role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol\/isread","abstract":[{"type":"text","text":"Inbox Message which is read, see + (void)readMessagesWithCodes:(NSArray<NSString *> *)codes"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRead","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRead"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageProtocol":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWInboxMessageProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"PWInboxMessageProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageProtocol","title":"PWInboxMessageProtocol","abstract":[{"type":"codeVoice","code":"PWInboxMessageProtocol"},{"type":"text","text":" The protocol describing the Inbox message."}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinboxmessageprotocol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isRead","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isRead"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRead"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"isRead","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isRead\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol~1isRead\/fragments","op":"replace","value":[{"text":"isRead","kind":"identifier"}]},{"value":"PWInboxMessageProtocol","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageProtocol\/fragments","op":"replace","value":[{"text":"PWInboxMessageProtocol","kind":"identifier"}]}]}]}