{"metadata":{"title":"PWCornerTypeTopLeft","role":"symbol","navigatorTitle":[{"text":"PWCornerTypeTopLeft","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"PWCornerTypeTopLeft","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","kind":"typeIdentifier","text":"CornerType"}],"symbolKind":"property","externalID":"c:@E@CornerType@PWCornerTypeTopLeft","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopLeft","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"PWCornerTypeTopLeft","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","text":"CornerType","preciseIdentifier":"c:@E@CornerType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopleft"]},{"paths":["\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopleft"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType/PWCornerTypeTopLeft":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWCornerTypeTopLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CornerType","text":"CornerType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWCornerTypeTopLeft"}],"role":"symbol","abstract":[],"title":"PWCornerTypeTopLeft","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType\/PWCornerTypeTopLeft","url":"\/documentation\/pushwooshframework\/cornertype\/pwcornertypetopleft"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/CornerType":{"navigatorTitle":[{"text":"CornerType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CornerType","kind":"identifier"}],"title":"CornerType","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/CornerType","kind":"symbol","url":"\/documentation\/pushwooshframework\/cornertype","abstract":[{"text":"Enum options defining the corners that can be rounded in a modal window.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PWCornerTypeTopLeft","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWCornerTypeTopLeft"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWCornerTypeTopLeft"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopLeft\/title","op":"replace","value":"PWCornerTypeTopLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType~1PWCornerTypeTopLeft\/fragments","value":[{"text":"PWCornerTypeTopLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/title","value":"CornerType"},{"value":[{"kind":"identifier","text":"CornerType"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1CornerType\/fragments"}]}]}