{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfrombottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfrombottom"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"PWAnimationPresentFromBottom","kind":"identifier"}],"title":"PresentModalWindowAnimation.PWAnimationPresentFromBottom","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"externalID":"c:@E@PresentModalWindowAnimation@PWAnimationPresentFromBottom","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromBottom"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentModalWindowAnimation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"abstract":[{"type":"text","text":"Enum defining the animation styles for presenting the modal window."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation","title":"PresentModalWindowAnimation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PresentModalWindowAnimation/PWAnimationPresentFromBottom":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PresentModalWindowAnimation\/PWAnimationPresentFromBottom","navigatorTitle":[{"text":"PWAnimationPresentFromBottom","kind":"identifier"}],"title":"PresentModalWindowAnimation.PWAnimationPresentFromBottom","url":"\/documentation\/pushwooshframework\/presentmodalwindowanimation\/pwanimationpresentfrombottom","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWAnimationPresentFromBottom","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWAnimationPresentFromBottom","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWAnimationPresentFromBottom"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PresentModalWindowAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation\/fragments","value":[{"kind":"identifier","text":"PresentModalWindowAnimation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromBottom\/title","value":"PWAnimationPresentFromBottom","op":"replace"},{"op":"replace","value":[{"text":"PWAnimationPresentFromBottom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PresentModalWindowAnimation~1PWAnimationPresentFromBottom\/fragments"}]}]}