{"variants":[{"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissright"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissright"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWSwipeDismissRight"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"text":"PWSwipeDismissRight","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@DismissSwipeDirection@PWSwipeDismissRight","title":"DismissSwipeDirection.PWSwipeDismissRight","roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissRight","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissRight"}],"languages":["swift"]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissRight":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissRight"}],"navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissRight"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissright","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissRight","title":"DismissSwipeDirection.PWSwipeDismissRight"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection":{"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissSwipeDirection"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection","title":"DismissSwipeDirection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PWSwipeDismissRight"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PWSwipeDismissRight","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PWSwipeDismissRight","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"PWSwipeDismissRight","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissRight\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissRight\/fragments","value":[{"text":"PWSwipeDismissRight","kind":"identifier"}],"op":"replace"},{"value":"DismissSwipeDirection","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/fragments","value":[{"kind":"identifier","text":"DismissSwipeDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}