{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissnone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissnone"]}],"metadata":{"symbolKind":"case","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"PWSwipeDismissNone","kind":"identifier"}],"externalID":"c:@E@DismissSwipeDirection@PWSwipeDismissNone","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWSwipeDismissNone","kind":"identifier"}],"title":"DismissSwipeDirection.PWSwipeDismissNone"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissNone"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWSwipeDismissNone","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection"]]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissNone":{"navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissNone"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissNone","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWSwipeDismissNone","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissnone","title":"DismissSwipeDirection.PWSwipeDismissNone"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection":{"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissSwipeDirection"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection","title":"DismissSwipeDirection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PWSwipeDismissNone","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PWSwipeDismissNone"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PWSwipeDismissNone","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissNone\/title","value":"PWSwipeDismissNone"},{"value":[{"kind":"identifier","text":"PWSwipeDismissNone"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissNone\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/title","value":"DismissSwipeDirection","op":"replace"},{"value":[{"text":"DismissSwipeDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}