{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwloglevel\/debug"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwloglevel\/debug"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","title":"debug","modules":[{"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"PWLogLevelDebug","kind":"identifier"}],"externalID":"c:@PWLogLevelDebug","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/debug","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel":{"url":"\/documentation\/pushwooshframework\/pwloglevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","abstract":[],"kind":"symbol","title":"PWLogLevel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/debug":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/debug","title":"debug","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwloglevel\/debug","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"}],"navigatorTitle":[{"text":"PWLogLevelDebug","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PWLogLevelDebug","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"kind":"identifier","text":"PWLogLevelDebug"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"PWLogLevelDebug","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/title","op":"replace","value":"PWLogLevel"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/fragments","op":"replace","value":[{"text":"PWLogLevel","kind":"identifier"}]},{"value":"PWLogLevelDebug","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1debug\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"PWLogLevelDebug"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}