{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwlog\/setlogshandler(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwlog\/setlogshandler(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLogsHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"logsHandler","kind":"internalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:PWLog.h@T@PWLogLevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","text":"PWLogLevel","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/setLogsHandler(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"setLogsHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLogsHandler","kind":"identifier"},{"text":"(((","kind":"text"},{"preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)PWLog(cm)setLogsHandler:","title":"setLogsHandler(_:)","roleHeading":"Type Method","symbolKind":"method"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel":{"url":"\/documentation\/pushwooshframework\/pwloglevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","abstract":[],"kind":"symbol","title":"PWLogLevel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLog/setLogsHandler(_:)":{"abstract":[],"kind":"symbol","type":"topic","title":"setLogsHandler(_:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLogsHandler"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"},{"text":"?, ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"setLogsHandler:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwlog\/setlogshandler(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog\/setLogsHandler(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLog":{"abstract":[],"kind":"symbol","type":"topic","title":"PWLog","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWLog","kind":"identifier"}],"navigatorTitle":[{"text":"PWLog","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwlog","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLog"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"setLogsHandler:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setLogsHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setLogsHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"level","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"logsHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/title","value":"PWLogLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/fragments","value":[{"text":"PWLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1setLogsHandler(_:)\/title","value":"setLogsHandler:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog~1setLogsHandler(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLogsHandler:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog\/title","value":"PWLog"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLog\/fragments","op":"replace","value":[{"text":"PWLog","kind":"identifier"}]}]}]}