{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/info","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","text":"PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwloglevel\/info"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwloglevel\/info"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"info","extendedModule":"PushwooshFramework","navigatorTitle":[{"kind":"identifier","text":"PWLogLevelInfo"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","text":"PWLogLevel"}],"roleHeading":"Type Property","modules":[{"name":"PushwooshFramework"}],"symbolKind":"property","externalID":"c:@PWLogLevelInfo"},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/info":{"url":"\/documentation\/pushwooshframework\/pwloglevel\/info","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/info","role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"info","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"PWLogLevelInfo","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel":{"url":"\/documentation\/pushwooshframework\/pwloglevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","abstract":[],"kind":"symbol","title":"PWLogLevel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PWLogLevelInfo","path":"\/metadata\/title","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWLogLevelInfo","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWLogLevelInfo"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1info\/title","value":"PWLogLevelInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1info\/fragments","op":"replace","value":[{"text":"PWLogLevelInfo","kind":"identifier"}]},{"op":"replace","value":"PWLogLevel","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PWLogLevel"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}