{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwloglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwloglevel\/warning"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/warning","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","title":"warning","symbolKind":"property","navigatorTitle":[{"text":"PWLogLevelWarning","kind":"identifier"}],"externalID":"c:@PWLogLevelWarning","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","text":"PWLogLevel","preciseIdentifier":"c:PWLog.h@T@PWLogLevel","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel/warning":{"role":"symbol","type":"topic","title":"warning","navigatorTitle":[{"kind":"identifier","text":"PWLogLevelWarning"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwloglevel\/warning","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel\/warning","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:PWLog.h@T@PWLogLevel"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWLogLevel":{"url":"\/documentation\/pushwooshframework\/pwloglevel","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWLogLevel","abstract":[],"kind":"symbol","title":"PWLogLevel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PWLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWLogLevel"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"PWLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"kind":"identifier","text":"PWLogLevelWarning"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"PWLogLevelWarning","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"PWLogLevelWarning","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1warning\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel~1warning\/fragments","value":[{"text":"PWLogLevelWarning","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/title","op":"replace","value":"PWLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWLogLevel\/fragments","value":[{"text":"PWLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}