{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"PushwooshFramework"}],"externalID":"c:@E@ModalWindowPosition@PWModalWindowPositionBottomSheet","roleHeading":"Case","role":"symbol","title":"ModalWindowPosition.PWModalWindowPositionBottomSheet","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowPositionBottomSheet"}],"navigatorTitle":[{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionbottomsheet"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionbottomsheet"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionBottomSheet"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottomSheet"},"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionBottomSheet":{"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionbottomsheet","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionBottomSheet","role":"symbol","abstract":[],"type":"topic","title":"ModalWindowPosition.PWModalWindowPositionBottomSheet","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionBottomSheet"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PWModalWindowPositionBottomSheet","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWModalWindowPositionBottomSheet"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PWModalWindowPositionBottomSheet","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottomSheet\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionBottomSheet\/fragments","value":[{"text":"PWModalWindowPositionBottomSheet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title","value":"ModalWindowPosition"},{"op":"replace","value":[{"kind":"identifier","text":"ModalWindowPosition"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments"}]}]}