{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionfullscreen"]},{"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionfullscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionFullScreen","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionFullScreen"}],"title":"ModalWindowPosition.PWModalWindowPositionFullScreen","roleHeading":"Case","externalID":"c:@E@ModalWindowPosition@PWModalWindowPositionFullScreen"},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionFullScreen":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"title":"ModalWindowPosition.PWModalWindowPositionFullScreen","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionFullScreen","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionFullScreen","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositionfullscreen"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PWModalWindowPositionFullScreen"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"PWModalWindowPositionFullScreen"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWModalWindowPositionFullScreen"}],"languages":["occ"]}]}},{"value":"ModalWindowPosition","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments","value":[{"text":"ModalWindowPosition","kind":"identifier"}]},{"op":"replace","value":"PWModalWindowPositionFullScreen","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionFullScreen\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionFullScreen\/fragments","value":[{"kind":"identifier","text":"PWModalWindowPositionFullScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}