{"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionTop","interfaceLanguage":"swift"},"metadata":{"title":"ModalWindowPosition.PWModalWindowPositionTop","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionTop"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:@E@ModalWindowPosition@PWModalWindowPositionTop","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionTop"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionTop"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiontop"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiontop"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionTop":{"title":"ModalWindowPosition.PWModalWindowPositionTop","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionTop","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWModalWindowPositionTop","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositiontop","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PWModalWindowPositionTop","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PWModalWindowPositionTop","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PWModalWindowPositionTop","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PWModalWindowPositionTop","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"PWModalWindowPositionTop","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionTop\/title"},{"value":[{"text":"PWModalWindowPositionTop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionTop\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title","value":"ModalWindowPosition"},{"value":[{"text":"ModalWindowPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments"}]}]}