{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"case","title":"ModalWindowPosition.PWModalWindowPositionCenter","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"roleHeading":"Case","navigatorTitle":[{"text":"PWModalWindowPositionCenter","kind":"identifier"}],"role":"symbol","externalID":"c:@E@ModalWindowPosition@PWModalWindowPositionCenter"},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionCenter","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWModalWindowPositionCenter","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositioncenter"]},{"paths":["\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositioncenter"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition":{"title":"ModalWindowPosition","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalWindowPosition","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition","abstract":[{"type":"text","text":"Enum defining the possible positions for displaying a modal window."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalWindowPosition"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/ModalWindowPosition/PWModalWindowPositionCenter":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/ModalWindowPosition\/PWModalWindowPositionCenter","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"navigatorTitle":[{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"url":"\/documentation\/pushwooshframework\/modalwindowposition\/pwmodalwindowpositioncenter","role":"symbol","title":"ModalWindowPosition.PWModalWindowPositionCenter"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWModalWindowPositionCenter","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWModalWindowPositionCenter","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PWModalWindowPositionCenter"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/title","value":"ModalWindowPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition\/fragments","value":[{"kind":"identifier","text":"ModalWindowPosition"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionCenter\/title","op":"replace","value":"PWModalWindowPositionCenter"},{"value":[{"text":"PWModalWindowPositionCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1ModalWindowPosition~1PWModalWindowPositionCenter\/fragments","op":"replace"}]}]}