{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/push","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PushwooshFramework"}],"role":"symbol","title":"PWRichMediaSource.push","externalID":"c:@E@PWRichMediaSource@PWRichMediaSourcePush","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSourcePush"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"push"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"codeListing","syntax":null,"code":[" RichMedia is presented from push notification."]}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediasource\/push"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediasource\/push"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource/push":{"abstract":[],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediasource\/push","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource\/push","navigatorTitle":[{"text":"PWRichMediaSourcePush","kind":"identifier"}],"title":"PWRichMediaSource.push"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaSource":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaSource","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaSource"}],"url":"\/documentation\/pushwooshframework\/pwrichmediasource","title":"PWRichMediaSource","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWRichMediaSource","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PWRichMediaSourcePush","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWRichMediaSourcePush"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWRichMediaSourcePush"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PWRichMediaSourcePush","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1push\/title"},{"value":[{"text":"PWRichMediaSourcePush","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource~1push\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/title","op":"replace","value":"PWRichMediaSource"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaSource\/fragments","value":[{"kind":"identifier","text":"PWRichMediaSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}