{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager"},{"kind":"text","text":"!, "},{"text":"didClose","kind":"externalParam"},{"kind":"text","text":" "},{"text":"richMedia","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}],"externalID":"c:objc(pl)PWRichMediaPresentingDelegate(im)richMediaManager:didCloseRichMedia:","title":"richMediaManager(_:didClose:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"kind":"text","text":"("},{"text":"PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didClose"},{"text":": ","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"kind":"text","text":"!)"}],"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didclose:)"]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didclose:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didClose:)"},"abstract":[{"text":"Tells the delegate that Rich Media has been closed.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:didClose:)":{"kind":"symbol","type":"topic","title":"richMediaManager(_:didClose:)","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didclose:)","role":"symbol","navigatorTitle":[{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didClose:)","abstract":[{"text":"Tells the delegate that Rich Media has been closed.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager"},{"text":"!, ","kind":"text"},{"text":"didClose","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":"!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"richMediaManager:didCloseRichMedia:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"richMediaManager:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","text":"PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"richMediaManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCloseRichMedia:"},{"text":"(","kind":"text"},{"text":"PWRichMedia","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"richMedia"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title","value":"PWRichMedia","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments","value":[{"kind":"identifier","text":"PWRichMedia"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title","value":"PWRichMediaManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWRichMediaManager"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didClose:)\/title","value":"richMediaManager:didCloseRichMedia:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didClose:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"richMediaManager:didCloseRichMedia:","kind":"identifier"}]},{"value":"PWRichMediaPresentingDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments"}]}]}