{"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"richMediaManager(_:didPresent:)","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)PWRichMediaPresentingDelegate(im)richMediaManager:didPresentRichMedia:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"didPresent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWRichMedia","preciseIdentifier":"c:objc(cs)PWRichMedia"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"richMediaManager:didPresentRichMedia:"}],"symbolKind":"method","required":true},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didPresent:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"richMediaManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PWRichMediaManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didPresent"},{"text":" ","kind":"text"},{"text":"richMedia","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","text":"PWRichMedia"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didpresent:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didpresent:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that Rich Media has been displayed."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMedia":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWRichMedia"}],"navigatorTitle":[{"text":"PWRichMedia","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmedia","title":"PWRichMedia","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate/richMediaManager(_:didPresent:)":{"abstract":[{"type":"text","text":"Tells the delegate that Rich Media has been displayed."}],"navigatorTitle":[{"text":"richMediaManager:didPresentRichMedia:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate\/richMediaManager(_:didPresent:)","title":"richMediaManager(_:didPresent:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMediaManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMediaManager","text":"PWRichMediaManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"didPresent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRichMedia","text":"PWRichMedia"},{"text":"!)","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate\/richmediamanager(_:didpresent:)","type":"topic","kind":"symbol","required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","title":"PWRichMediaManager","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediamanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaPresentingDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWRichMediaPresentingDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaPresentingDelegate","title":"PWRichMediaPresentingDelegate","abstract":[{"text":"Interface for Rich Media presentation managing.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediapresentingdelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"richMediaManager:didPresentRichMedia:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:didPresentRichMedia:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"richMediaManager:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaManager","text":"PWRichMediaManager","preciseIdentifier":"c:objc(cs)PWRichMediaManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"richMediaManager"},{"kind":"text","text":" "},{"text":"didPresentRichMedia:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRichMedia","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMedia","text":"PWRichMedia"},{"kind":"text","text":" *) "},{"text":"richMedia","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"PWRichMedia","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMedia\/fragments","value":[{"text":"PWRichMedia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didPresent:)\/title","value":"richMediaManager:didPresentRichMedia:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate~1richMediaManager(_:didPresent:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"richMediaManager:didPresentRichMedia:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/title","value":"PWRichMediaManager","op":"replace"},{"value":[{"text":"PWRichMediaManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/title","value":"PWRichMediaPresentingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaPresentingDelegate\/fragments","op":"replace","value":[{"text":"PWRichMediaPresentingDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}