{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PWSwipeDismissUp","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissup"]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@DismissSwipeDirection@PWSwipeDismissUp","title":"DismissSwipeDirection.PWSwipeDismissUp","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWSwipeDismissUp"}],"navigatorTitle":[{"kind":"identifier","text":"PWSwipeDismissUp"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissUp"},"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection":{"navigatorTitle":[{"kind":"identifier","text":"DismissSwipeDirection"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DismissSwipeDirection"}],"url":"\/documentation\/pushwooshframework\/dismissswipedirection","title":"DismissSwipeDirection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissSwipeDirection/PWSwipeDismissUp":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWSwipeDismissUp"}],"navigatorTitle":[{"text":"PWSwipeDismissUp","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/dismissswipedirection\/pwswipedismissup","abstract":[],"title":"DismissSwipeDirection.PWSwipeDismissUp","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissSwipeDirection\/PWSwipeDismissUp","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"PWSwipeDismissUp","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWSwipeDismissUp"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PWSwipeDismissUp","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/title","value":"DismissSwipeDirection"},{"value":[{"text":"DismissSwipeDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection\/fragments"},{"value":"PWSwipeDismissUp","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissUp\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissSwipeDirection~1PWSwipeDismissUp\/fragments","value":[{"text":"PWSwipeDismissUp","kind":"identifier"}],"op":"replace"}]}]}