{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissDown","kind":"identifier"}]}]}],"sections":[],"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWAnimationDismissDown"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"PWAnimationDismissDown","kind":"identifier"}],"externalID":"c:@E@DismissModalWindowAnimation@PWAnimationDismissDown","title":"DismissModalWindowAnimation.PWAnimationDismissDown"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDown"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdown"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissDown":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissDown","kind":"identifier"}],"navigatorTitle":[{"text":"PWAnimationDismissDown","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdown","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDown","title":"DismissModalWindowAnimation.PWAnimationDismissDown"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PWAnimationDismissDown"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWAnimationDismissDown"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"PWAnimationDismissDown","kind":"identifier"}],"languages":["occ"]}]}},{"value":"PWAnimationDismissDown","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDown\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDown\/fragments","value":[{"kind":"identifier","text":"PWAnimationDismissDown"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title","value":"DismissModalWindowAnimation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments","value":[{"kind":"identifier","text":"DismissModalWindowAnimation"}],"op":"replace"}]}]}