{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","title":"DismissModalWindowAnimation.PWAnimationDismissLeft","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWAnimationDismissLeft","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PWAnimationDismissLeft"}],"externalID":"c:@E@DismissModalWindowAnimation@PWAnimationDismissLeft","modules":[{"name":"PushwooshFramework"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissLeft","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissLeft"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissleft"]},{"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissleft"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissLeft":{"navigatorTitle":[{"text":"PWAnimationDismissLeft","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissLeft"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissLeft","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissLeft","abstract":[],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PWAnimationDismissLeft"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PWAnimationDismissLeft","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PWAnimationDismissLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWAnimationDismissLeft","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissLeft\/title"},{"value":[{"kind":"identifier","text":"PWAnimationDismissLeft"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissLeft\/fragments"},{"value":"DismissModalWindowAnimation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title"},{"op":"replace","value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}