{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDefault","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"]]},"metadata":{"title":"DismissModalWindowAnimation.PWAnimationDismissDefault","externalID":"c:@E@DismissModalWindowAnimation@PWAnimationDismissDefault","role":"symbol","navigatorTitle":[{"text":"PWAnimationDismissDefault","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissDefault"}],"modules":[{"name":"PushwooshFramework"}],"symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdefault"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdefault"]}],"abstract":[{"type":"text","text":"Default dismiss animation is "},{"type":"codeVoice","code":"PWAnimationCurveEaseInOut"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWAnimationDismissDefault","kind":"identifier"}]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissDefault":{"navigatorTitle":[{"kind":"identifier","text":"PWAnimationDismissDefault"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissdefault","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAnimationDismissDefault","kind":"identifier"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissDefault","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissDefault","abstract":[{"type":"text","text":"Default dismiss animation is "},{"type":"codeVoice","code":"PWAnimationCurveEaseInOut"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"PWAnimationDismissDefault","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PWAnimationDismissDefault","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWAnimationDismissDefault"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDefault\/title","value":"PWAnimationDismissDefault","op":"replace"},{"op":"replace","value":[{"text":"PWAnimationDismissDefault","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissDefault\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title","value":"DismissModalWindowAnimation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments","value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"op":"replace"}]}]}