{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"case","externalID":"c:@E@DismissModalWindowAnimation@PWAnimationDismissRight","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissRight"}],"role":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissRight","roleHeading":"Case","navigatorTitle":[{"text":"PWAnimationDismissRight","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissRight","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PWAnimationDismissRight","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissright"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation/PWAnimationDismissRight":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation\/PWAnimationDismissRight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWAnimationDismissRight"}],"url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation\/pwanimationdismissright","role":"symbol","kind":"symbol","title":"DismissModalWindowAnimation.PWAnimationDismissRight","type":"topic","navigatorTitle":[{"text":"PWAnimationDismissRight","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/DismissModalWindowAnimation":{"abstract":[{"text":"Enum defining the animation styles for dismissing the modal window.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/DismissModalWindowAnimation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DismissModalWindowAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/dismissmodalwindowanimation","title":"DismissModalWindowAnimation","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWAnimationDismissRight","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWAnimationDismissRight"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PWAnimationDismissRight","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"PWAnimationDismissRight","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation~1PWAnimationDismissRight\/fragments","value":[{"kind":"identifier","text":"PWAnimationDismissRight"}]},{"value":"DismissModalWindowAnimation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/title","op":"replace"},{"value":[{"text":"DismissModalWindowAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1DismissModalWindowAnimation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}