{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"plain","kind":"identifier"}],"symbolKind":"case","title":"PWInboxMessageType.plain","navigatorTitle":[{"text":"PWInboxMessageTypePlain","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:@E@PWInboxMessageType@PWInboxMessageTypePlain","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinboxmessagetype\/plain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinboxmessagetype\/plain"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"plain"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType\/plain","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInboxMessageType"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType","kind":"symbol","title":"PWInboxMessageType","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessageType"}],"url":"\/documentation\/pushwooshframework\/pwinboxmessagetype","abstract":[{"type":"text","text":"The Inbox message type. Plain = without any action, Richmedia = contains a Rich media page, URL = contains remote URL, Deeplink = contains Deeplink"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInboxMessageType/plain":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInboxMessageType\/plain","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"plain"}],"url":"\/documentation\/pushwooshframework\/pwinboxmessagetype\/plain","navigatorTitle":[{"text":"PWInboxMessageTypePlain","kind":"identifier"}],"title":"PWInboxMessageType.plain"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"PWInboxMessageTypePlain","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWInboxMessageTypePlain","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PWInboxMessageTypePlain"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"PWInboxMessageType","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType\/title"},{"value":[{"kind":"identifier","text":"PWInboxMessageType"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType~1plain\/title","value":"PWInboxMessageTypePlain"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInboxMessageType~1plain\/fragments","value":[{"text":"PWInboxMessageTypePlain","kind":"identifier"}]}]}]}