{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/allowsinlinemediaplayback"]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/allowsinlinemediaplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsInlineMediaPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"allowsInlineMediaPlayback"}],"externalID":"c:objc(cs)PWRichMediaStyle(py)allowsInlineMediaPlayback","symbolKind":"property","title":"allowsInlineMediaPlayback","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowsInlineMediaPlayback","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle"]]},"abstract":[{"type":"text","text":"A Boolean value that determines whether HTML5 videos play inline or use the native full-screen controller."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/allowsInlineMediaPlayback"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle/allowsInlineMediaPlayback":{"abstract":[{"text":"A Boolean value that determines whether HTML5 videos play inline or use the native full-screen controller.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsInlineMediaPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"allowsInlineMediaPlayback","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyle\/allowsinlinemediaplayback","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/allowsInlineMediaPlayback","title":"allowsInlineMediaPlayback"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyle","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyle","abstract":[{"type":"text","text":"‘PWRichMediaStyle’ class allows customizing the appearance of Rich Media pages."}],"kind":"symbol","title":"PWRichMediaStyle","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyle"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"allowsInlineMediaPlayback"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"allowsInlineMediaPlayback","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"allowsInlineMediaPlayback"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1allowsInlineMediaPlayback\/title","value":"allowsInlineMediaPlayback"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1allowsInlineMediaPlayback\/fragments","value":[{"text":"allowsInlineMediaPlayback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/title","value":"PWRichMediaStyle","op":"replace"},{"value":[{"text":"PWRichMediaStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}