{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/animationdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/animationdelegate"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Delegate to manage Rich Media presenting animation."}],"metadata":{"symbolKind":"property","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWRichMediaStyle(py)animationDelegate","navigatorTitle":[{"kind":"identifier","text":"animationDelegate"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWRichMediaStyleAnimationDelegate","text":"PWRichMediaStyleAnimationDelegate","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"roleHeading":"Instance Property","title":"animationDelegate","role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"PWRichMediaStyleAnimationDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate","preciseIdentifier":"c:objc(pl)PWRichMediaStyleAnimationDelegate","kind":"typeIdentifier"},{"kind":"text","text":")! { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/animationDelegate","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle/animationDelegate":{"abstract":[{"text":"Delegate to manage Rich Media presenting animation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"PWRichMediaStyleAnimationDelegate","preciseIdentifier":"c:objc(pl)PWRichMediaStyleAnimationDelegate","kind":"typeIdentifier"},{"kind":"text","text":")!"}],"navigatorTitle":[{"text":"animationDelegate","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyle\/animationdelegate","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/animationDelegate","title":"animationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyle","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyle","abstract":[{"type":"text","text":"‘PWRichMediaStyle’ class allows customizing the appearance of Rich Media pages."}],"kind":"symbol","title":"PWRichMediaStyle","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyle"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyleAnimationDelegate":{"abstract":[{"text":"Interface for Rich Media Custom Animation.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyleanimationdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyleAnimationDelegate","navigatorTitle":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}],"title":"PWRichMediaStyleAnimationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"animationDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"animationDelegate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)PWRichMediaStyleAnimationDelegate","kind":"typeIdentifier","text":"id<PWRichMediaStyleAnimationDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1animationDelegate\/title","value":"animationDelegate"},{"op":"replace","value":[{"text":"animationDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1animationDelegate\/fragments"},{"value":"PWRichMediaStyle","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/title","op":"replace"},{"value":[{"text":"PWRichMediaStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/fragments"},{"value":"PWRichMediaStyleAnimationDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyleAnimationDelegate\/fragments","value":[{"text":"PWRichMediaStyleAnimationDelegate","kind":"identifier"}]}]}]}