{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"symbolKind":"property","modules":[{"name":"PushwooshFramework"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"!","kind":"text"}],"externalID":"c:objc(cs)PWRichMediaStyle(py)backgroundColor","title":"backgroundColor","roleHeading":"Instance Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/backgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/backgroundcolor"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/backgroundColor","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle/backgroundColor":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyle\/backgroundcolor","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/backgroundColor","title":"backgroundColor"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyle","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyle","abstract":[{"type":"text","text":"‘PWRichMediaStyle’ class allows customizing the appearance of Rich Media pages."}],"kind":"symbol","title":"PWRichMediaStyle","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyle"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"backgroundColor","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"backgroundColor","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1backgroundColor\/title","value":"backgroundColor"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1backgroundColor\/fragments","op":"replace","value":[{"text":"backgroundColor","kind":"identifier"}]},{"op":"replace","value":"PWRichMediaStyle","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/title"},{"value":[{"text":"PWRichMediaStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}