{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"loadingViewBlock","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:PWRichMediaStyle.h@T@PWRichMediaLoadingViewBlock","kind":"typeIdentifier","text":"PWRichMediaLoadingViewBlock","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaLoadingViewBlock"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/loadingviewblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/loadingviewblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/loadingViewBlock"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)PWRichMediaStyle(py)loadingViewBlock","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadingViewBlock"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PWRichMediaStyle.h@T@PWRichMediaLoadingViewBlock","text":"PWRichMediaLoadingViewBlock"},{"text":"!","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"loadingViewBlock"}],"symbolKind":"property","title":"loadingViewBlock","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaLoadingViewBlock":{"type":"topic","navigatorTitle":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"abstract":[],"title":"PWRichMediaLoadingViewBlock","url":"\/documentation\/pushwooshframework\/pwrichmedialoadingviewblock","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaLoadingViewBlock"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyle","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyle","abstract":[{"type":"text","text":"‘PWRichMediaStyle’ class allows customizing the appearance of Rich Media pages."}],"kind":"symbol","title":"PWRichMediaStyle","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyle"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle/loadingViewBlock":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"loadingViewBlock","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:PWRichMediaStyle.h@T@PWRichMediaLoadingViewBlock","text":"PWRichMediaLoadingViewBlock","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"loadingViewBlock","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyle\/loadingviewblock","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/loadingViewBlock","title":"loadingViewBlock"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"loadingViewBlock","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"loadingViewBlock","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:PWRichMediaStyle.h@T@PWRichMediaLoadingViewBlock","kind":"typeIdentifier","text":"PWRichMediaLoadingViewBlock","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaLoadingViewBlock"},{"kind":"text","text":" "},{"text":"loadingViewBlock","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaLoadingViewBlock\/title","op":"replace","value":"PWRichMediaLoadingViewBlock"},{"value":[{"text":"PWRichMediaLoadingViewBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaLoadingViewBlock\/fragments"},{"op":"replace","value":"PWRichMediaStyle","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/fragments","value":[{"kind":"identifier","text":"PWRichMediaStyle"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1loadingViewBlock\/title","value":"loadingViewBlock","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"loadingViewBlock"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1loadingViewBlock\/fragments"}]}]}