{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlaybackRequiresUserAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/mediaplaybackrequiresuseraction"]},{"paths":["\/documentation\/pushwooshframework\/pwrichmediastyle\/mediaplaybackrequiresuseraction"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/mediaPlaybackRequiresUserAction"},"abstract":[{"text":"A Boolean value that determines whether HTML5 videos can play automatically or require the user to start playing them.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlaybackRequiresUserAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"mediaPlaybackRequiresUserAction"}],"externalID":"c:objc(cs)PWRichMediaStyle(py)mediaPlaybackRequiresUserAction","symbolKind":"property","roleHeading":"Instance Property","title":"mediaPlaybackRequiresUserAction","role":"symbol"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWRichMediaStyle","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwrichmediastyle","abstract":[{"type":"text","text":"‘PWRichMediaStyle’ class allows customizing the appearance of Rich Media pages."}],"kind":"symbol","title":"PWRichMediaStyle","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle","navigatorTitle":[{"kind":"identifier","text":"PWRichMediaStyle"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWRichMediaStyle/mediaPlaybackRequiresUserAction":{"abstract":[{"text":"A Boolean value that determines whether HTML5 videos can play automatically or require the user to start playing them.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaPlaybackRequiresUserAction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"mediaPlaybackRequiresUserAction","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pwrichmediastyle\/mediaplaybackrequiresuseraction","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWRichMediaStyle\/mediaPlaybackRequiresUserAction","title":"mediaPlaybackRequiresUserAction"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mediaPlaybackRequiresUserAction"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mediaPlaybackRequiresUserAction"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mediaPlaybackRequiresUserAction"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/title","value":"PWRichMediaStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle\/fragments","value":[{"kind":"identifier","text":"PWRichMediaStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1mediaPlaybackRequiresUserAction\/title","value":"mediaPlaybackRequiresUserAction"},{"op":"replace","value":[{"text":"mediaPlaybackRequiresUserAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWRichMediaStyle~1mediaPlaybackRequiresUserAction\/fragments"}]}]}