{"abstract":[{"type":"text","text":"Tells the delegate that In-App Message load stated"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartload(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartload(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onWebViewStartLoad"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"webView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"text":"!)","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:objc(pl)PWJavaScriptInterface(im)onWebViewStartLoad:","title":"onWebViewStartLoad(_:)","required":true,"platforms":[{"introducedAt":"8.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onWebViewStartLoad"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":"!)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"onWebViewStartLoad:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartLoad(_:)"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface/onWebViewStartLoad(_:)":{"kind":"symbol","title":"onWebViewStartLoad(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface\/onWebViewStartLoad(_:)","role":"symbol","navigatorTitle":[{"text":"onWebViewStartLoad:","kind":"identifier"}],"required":true,"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface\/onwebviewstartload(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onWebViewStartLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"abstract":[{"text":"Tells the delegate that In-App Message load stated","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","abstract":[{"code":"PWJavaScriptInterface","type":"codeVoice"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"text":" ","type":"text"},{"text":"to provide native calls and callbacks to Objective-C\/Swift.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface","navigatorTitle":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"kind":"symbol","title":"PWJavaScriptInterface","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWJavaScriptInterface","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onWebViewStartLoad:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"onWebViewStartLoad:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onWebViewStartLoad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onWebViewStartLoad:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartLoad(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface~1onWebViewStartLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onWebViewStartLoad:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/title","value":"PWJavaScriptInterface"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/fragments","value":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"op":"replace"}]}]}