{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didChangeSizeOfInline(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate"]]},"metadata":{"title":"didChangeSizeOfInline(_:)","externalID":"c:objc(pl)PWInlineInAppViewDelegate(im)didChangeSizeOfInlineInAppView:","role":"symbol","required":true,"navigatorTitle":[{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeSizeOfInline"},{"kind":"text","text":"("},{"text":"PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didchangesizeofinline(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didchangesizeofinline(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeSizeOfInline"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inAppView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PWInlineInAppView","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView","kind":"typeIdentifier"},{"kind":"text","text":"!)"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate","title":"PWInlineInAppViewDelegate","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/didChangeSizeOfInline(_:)":{"type":"topic","kind":"symbol","title":"didChangeSizeOfInline(_:)","required":true,"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didchangesizeofinline(_:)","abstract":[],"navigatorTitle":[{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didChangeSizeOfInline(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didChangeSizeOfInline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"kind":"text","text":"!)"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview","title":"PWInlineInAppView","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppView"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"didChangeSizeOfInlineInAppView:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"didChangeSizeOfInlineInAppView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWInlineInAppView","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inAppView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/title","value":"PWInlineInAppViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/fragments","value":[{"text":"PWInlineInAppViewDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didChangeSizeOfInline(_:)\/title","op":"replace","value":"didChangeSizeOfInlineInAppView:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeSizeOfInlineInAppView:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didChangeSizeOfInline(_:)\/fragments"},{"op":"replace","value":"PWInlineInAppView","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/fragments","op":"replace","value":[{"text":"PWInlineInAppView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}