{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"title":"didCloseInline(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didCloseInline","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"kind":"text","text":"!)"}],"externalID":"c:objc(pl)PWInlineInAppViewDelegate(im)didCloseInlineInAppView:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"didCloseInlineInAppView:"}],"role":"symbol"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didCloseInline(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didCloseInline","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"inAppView","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWInlineInAppView","text":"PWInlineInAppView"},{"text":"!)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didcloseinline(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didcloseinline(_:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate","title":"PWInlineInAppViewDelegate","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInlineInAppView"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappview","title":"PWInlineInAppView","navigatorTitle":[{"kind":"identifier","text":"PWInlineInAppView"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInlineInAppViewDelegate/didCloseInline(_:)":{"abstract":[],"required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinlineinappviewdelegate\/didcloseinline(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didCloseInline","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PWInlineInAppView","kind":"typeIdentifier","text":"PWInlineInAppView"},{"text":"!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppViewDelegate\/didCloseInline(_:)","navigatorTitle":[{"kind":"identifier","text":"didCloseInlineInAppView:"}],"title":"didCloseInline(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"didCloseInlineInAppView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"didCloseInlineInAppView:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didCloseInlineInAppView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PWInlineInAppView","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInlineInAppView","preciseIdentifier":"c:objc(cs)PWInlineInAppView"},{"text":" *) ","kind":"text"},{"text":"inAppView","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/title","value":"PWInlineInAppViewDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWInlineInAppViewDelegate"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/title","op":"replace","value":"PWInlineInAppView"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppView\/fragments","value":[{"text":"PWInlineInAppView","kind":"identifier"}],"op":"replace"},{"value":"didCloseInlineInAppView:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didCloseInline(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInlineInAppViewDelegate~1didCloseInline(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didCloseInlineInAppView:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}