{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addJavascriptInterface"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interface","kind":"internalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"},{"kind":"text","text":" & "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","kind":"typeIdentifier","text":"PWJavaScriptInterface","preciseIdentifier":"c:objc(pl)PWJavaScriptInterface"},{"text":")!, ","kind":"text"},{"text":"withName","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!)","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)PWInAppManager(im)addJavascriptInterface:withName:","title":"addJavascriptInterface(_:withName:)","navigatorTitle":[{"text":"addJavascriptInterface:withName:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addJavascriptInterface","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWJavaScriptInterface","text":"PWJavaScriptInterface","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"kind":"externalParam","text":"withName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"symbolKind":"method","role":"symbol"},"abstract":[{"type":"text","text":"Adds javascript interface for In-App Messages. Interface will be accessible from javascript as object with specified "},{"type":"codeVoice","code":"name"},{"type":"text","text":" and functions defined in "},{"type":"codeVoice","code":"interface"},{"type":"text","text":" class."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/addJavascriptInterface(_:withName:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/addjavascriptinterface(_:withname:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/addjavascriptinterface(_:withname:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/addJavascriptInterface(_:withName:)":{"url":"\/documentation\/pushwooshframework\/pwinappmanager\/addjavascriptinterface(_:withname:)","role":"symbol","navigatorTitle":[{"text":"addJavascriptInterface:withName:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/addJavascriptInterface(_:withName:)","title":"addJavascriptInterface(_:withName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addJavascriptInterface","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWJavaScriptInterface","text":"PWJavaScriptInterface","kind":"typeIdentifier"},{"kind":"text","text":")!, "},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"type":"topic","abstract":[{"text":"Adds javascript interface for In-App Messages. Interface will be accessible from javascript as object with specified ","type":"text"},{"code":"name","type":"codeVoice"},{"text":" and functions defined in ","type":"text"},{"code":"interface","type":"codeVoice"},{"type":"text","text":" class."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager":{"url":"\/documentation\/pushwooshframework\/pwinappmanager","title":"PWInAppManager","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInAppManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWInAppManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWJavaScriptInterface":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWJavaScriptInterface","abstract":[{"code":"PWJavaScriptInterface","type":"codeVoice"},{"type":"text","text":" protocol is a representation of Javascript object that can be added at runtime into In-App Message HTML page"},{"text":" ","type":"text"},{"text":"to provide native calls and callbacks to Objective-C\/Swift.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwjavascriptinterface","navigatorTitle":[{"text":"PWJavaScriptInterface","kind":"identifier"}],"kind":"symbol","title":"PWJavaScriptInterface","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWJavaScriptInterface","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"addJavascriptInterface:withName:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addJavascriptInterface:withName:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addJavascriptInterface:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)PWJavaScriptInterface","text":"NSObject<PWJavaScriptInterface>"},{"text":" *) ","kind":"text"},{"text":"interface","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1addJavascriptInterface(_:withName:)\/title","op":"replace","value":"addJavascriptInterface:withName:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1addJavascriptInterface(_:withName:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addJavascriptInterface:withName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/title","value":"PWInAppManager"},{"value":[{"kind":"identifier","text":"PWInAppManager"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/title","value":"PWJavaScriptInterface"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWJavaScriptInterface\/fragments","op":"replace","value":[{"text":"PWJavaScriptInterface","kind":"identifier"}]}]}]}