{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setUserId:"}],"symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserId"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)PWInAppManager(im)setUserId:","title":"setUserId(_:)","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"text":" ","type":"text"},{"text":"This allows data and events to be matched across multiple user devices.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserId"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"userId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/setuserid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinappmanager\/setuserid(_:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager/setUserId(_:)":{"abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"type":"text","text":" "},{"text":"This allows data and events to be matched across multiple user devices.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager\/setUserId(_:)","url":"\/documentation\/pushwooshframework\/pwinappmanager\/setuserid(_:)","navigatorTitle":[{"kind":"identifier","text":"setUserId:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"kind":"symbol","role":"symbol","title":"setUserId(_:)","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInAppManager":{"url":"\/documentation\/pushwooshframework\/pwinappmanager","title":"PWInAppManager","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInAppManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInAppManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWInAppManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setUserId:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setUserId:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setUserId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"setUserId:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setUserId:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager~1setUserId(_:)\/fragments"},{"value":"PWInAppManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/title"},{"value":[{"text":"PWInAppManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInAppManager\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}